### ISSUE TITLE
[Feature] Translation license

### ISSUE THREAD

**Issue by comradekingu** [XayahSuSuSu/Android-DataBackup#105]
https://hosted.weblate.org/projects/databackup/#information says GPLv3-only _specifically_,
whereas it isn't specified either way (or-later, or -only) in https://github.com/XayahSuSuSu/Android-DataBackup

This means if a new A/GPLv4 comes out (and it is good), it won't be possible to switch to it (or the AGPLv3+) without asking every single translator first. That just seems worse to me.

It can be changed to GPLv3-or-later in
https://hosted.weblate.org/settings/databackup/app/
and
https://hosted.weblate.org/settings/databackup/glossary/

**Comment by XayahSuSuSu** [comment]
It has been changed to `GPLv3-or-later`, thanks for reminding:)

**Comment by comradekingu** [comment]
Top stuff :)
