### ISSUE TITLE
[Bug] MIUI14 DEV，打开app后只能看见一个黑点+白屏

### ISSUE THREAD

**Issue by AdamTyn** [XayahSuSuSu/Android-DataBackup#109]
MIUI14 DEV，打开app后只能看见一个黑点+白屏

**Comment by XayahSuSuSu** [comment]
能否提供截图

**Comment by AdamTyn** [comment]
https://user-images.githubusercontent.com/29447491/223674012-e8d75309-3029-43b3-ba9a-94534b10bfe6.mp4

**Comment by AdamTyn** [comment]
卸载重新安装也是一样的

**Comment by AdamTyn** [comment]
系统信息如图：
![Screenshot_2023-03-08-17-47-22-055_com android settings](https://user-images.githubusercontent.com/29447491/223679798-82e98dda-6dff-4ded-abfb-1860afff30e4.jpg)

**Comment by AdamTyn** [comment]
冻结app列表如图：
![Screenshot_2023-03-08-17-47-37-665_com aistra hail](https://user-images.githubusercontent.com/29447491/223679898-afa1e135-c0bb-41d5-bc42-9a6b4683cd53.jpg)

**Comment by XayahSuSuSu** [comment]
> 卸载重新安装也是一样的

Magisk版本是多少，试过其它1.0.0后缀的版本吗

**Comment by AdamTyn** [comment]
> 

你发的每个版本我都用过了
之前miui13都是可以用的
magisk 2.4.3

**Comment by XayahSuSuSu** [comment]
> > 
> 
> 你发的每个版本我都用过了 之前miui13都是可以用的 magisk 2.4.3

24.3？试试更新到25.2

**Comment by XayahSuSuSu** [comment]
无回复，暂时关闭
