### ISSUE TITLE
[Feature] 已备份的数据恢复时是否需要root

### ISSUE THREAD

**Issue by lym0929** [XayahSuSuSu/Android-DataBackup#114]
**Describe the feature**
A clear and concise description.
我是小米手机，现在是内测版备份是有root，但想重装系统稳定版 是没有root的，想问一下没有root时 已经备份的数据能恢复回去吗？

**Comment by XayahSuSuSu** [comment]
第三方数据备份应用备份和恢复均需要ROOT权限
