### ISSUE TITLE
Directory classification  

### ISSUE THREAD

**Issue by Subhashis2007** [XayahSuSuSu/Android-DataBackup#118]
If there would be an option to detect the previously backed up file to restore the items it would be good. 

Coz if we transfer the files to another directory and get them back to the directory to which we backed up.. it would be messy.

In shot.. an option to choose from where the app should get its files to restore them.🙂

Thank you for making this wonderful app.. without setting a payment option or paid version.

**Comment by XayahSuSuSu** [comment]
You mean something like an anchor to locate the backup files?

**Comment by subhashis-barad** [comment]
Yes bro, 
An option to choose where are the files that you had backed up earlier.

**Comment by XayahSuSuSu** [comment]
> Yes bro, An option to choose where are the files that you had backed up earlier.

`DataBackup` is forced to be the root dir of the backup, now we can choose it manually in settings.
E.g, `/storage/emulated/0/DataBackup` is the default path, assume that your earlier backup is under `/storage/emulated/0/$somewhere_else/DataBackup`, that's what you can set in settings.

**Comment by XayahSuSuSu** [comment]
> You mean something like an anchor to locate the backup files?

And it's also a great idea, will take it into account.

**Comment by subhashis-barad** [comment]
I got it. 
But I was saying about, a toggle that would allow us to choose where to pick up the backed up files to restore the items..

Like..

[Choose directory you want to restore from]

**Comment by XayahSuSuSu** [comment]
Will keep it open until the implementation is done.

**Comment by XayahSuSuSu** [comment]
Implemented in https://github.com/XayahSuSuSu/Android-DataBackup/commit/4b262c58a547d1ef9fc6aa437390630c0330cf70

**Comment by Subhashis2007** [comment]
Great
