### ISSUE TITLE
[Feature] 希望能增加OTG支持

### ISSUE THREAD

**Issue by xushet** [XayahSuSuSu/Android-DataBackup#119]
**Describe the feature**
A clear and concise description.
从otg恢复备份和备份至otg

**Comment by XayahSuSuSu** [comment]
设置中备份目录项点开会自动检测OTG，或者你可以手动选择`/mnt/media_rw/`下的OTG目录

**Comment by xushet** [comment]
> 设置中备份目录项点开会自动检测OTG，或者你可以手动选择`/mnt/media_rw/`下的OTG目录

啊这😨，有点太隐蔽加个小提示什么的会好点，还是谢谢了
（赶紧去备份先）
