### ISSUE TITLE
[Bug] Restore problem

### ISSUE THREAD

**Issue by Mahantor** [XayahSuSuSu/Android-DataBackup#120]
**Describe the bug**
Hello
After restoring some applications, some of their settings are reset, for example, I logged into the MT Manager application and had pinned a number of bookmarks and the program was set to dark mode, but every time after restoring the application, the bookmarks are deleted. and I need to login again and the dark mode settings are changed to light mode
This problem occurs to me in many other applications as well
Is this a bug? Is there a solution to this issue?

**Expected behavior**
Full restoration of apps without resetting their settings

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [xiaomi Redmi note 9 pro]
 - OS: [e.g. MIUI13, Android12]
 - Version [e.g. 1.0.1 alpha01]

**Additional context**

**Comment by XayahSuSuSu** [comment]
Can you offer a log in `DataBackup/backup/0/log`?

**Comment by Mahantor** [comment]
https://github.com/XayahSuSuSu/Android-DataBackup/assets/91434001/e98621e7-45d3-4b32-82a0-57d7e70f934f

**Comment by XayahSuSuSu** [comment]
Some apps don't use nornal ways to store loggin state and it's not easy to restore.
I tested MT manager, the bookmarks here were restored well while the loggin state weren't.
Maybe it validates something else like ssaid and that's not supported yet for backing up/restoring.

**Comment by Mahantor** [comment]
https://github.com/XayahSuSuSu/Android-DataBackup/assets/91434001/e98621e7-45d3-4b32-82a0-57d7e70f934f

    Ok thanks

**Comment by Mahantor** [comment]
> Some apps don't use nornal ways to store loggin state and it's not easy to restore.
> I tested MT manager, the bookmarks here were restored well while the loggin state wasn't.
> Maybe it validates something else like ssaid and that's not supported yet for backing up/restoring.

Ok thanks
