### ISSUE TITLE
[Bug] MIUI14 提示 RootService 连接失败

### ISSUE THREAD

**Issue by AdamTyn** [XayahSuSuSu/Android-DataBackup#125]
### 使用版本
1.0.0-alpha01   到   1.0.1-alpha01  所有版本

### 手机信息
- 红米 K40S 已经Root
- 安装 magisk24.3 到 magisk26.1 所有版本（包括 Magisk Delta 最新版本）
- 参数图
  - ![参数图](https://github.com/XayahSuSuSu/Android-DataBackup/assets/29447491/f86a59dd-8738-4e6f-8f7f-e4a59dc3ff4a)

**Comment by XayahSuSuSu** [comment]
看看Magisk manager截图

**Comment by AdamTyn** [comment]
我已经用beta 4.3.20备份了 现在刷机中
