### ISSUE TITLE
[优化] 中文下选择覆盖备份，路径下会有中文，adb pull报错

### ISSUE THREAD

**Issue by mywp** [XayahSuSuSu/Android-DataBackup#129]
中文下选择覆盖备份方式，路径下会有中文，adb pull报错
选择另一种备份方式正常

DataBackup-1.0.1-alpha01-arm64-v8a-premium-release.apk

![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/12216939/7d8fb8fd-68a9-4c83-997e-5458c4113195)

**Comment by XayahSuSuSu** [comment]
这个应该是adb对中文字符的兼容问题，对于“覆盖”策略，后续更新应该会同一使用英文作为目录名

**Comment by XayahSuSuSu** [comment]
新版本(1.1.0开始)不再以中文路径命名，应该已经解决了此类问题
