### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by digirus808** [XayahSuSuSu/Android-DataBackup#133]
**Describe the bug**
I have backuped my apps and other things recently on my poco x3 pro (running latest PE13) and transfered the databackup file to my poco f3 (running pixelos latest). I copied the databackup folder to the folder of my Poco F3. Chose the right directory in interal storage, however the apps are not shown and there is no way to restore anything. What is the correct way to copy the folder to the new phone and directory so the data shows in the databackup list. 

**To Reproduce**
1. Backed everything up on X3 PRO, transferred databackup folder to pc and then to Poco F3 databackup folder
2. chose right directory to show
3. Chose button restore apps but nothings shows to be restored

**Expected behavior**
Apps should be shown to restore all data

**Smartphone (please complete the following information):**
 - Old phone with backup: Poco X3 PRO PIXEL EXPerience 13, new Phone Poco F3 running latest Pixel OS. 
 

**Additional context**
Is it impssible to switch data between phones or is there a way to make this work?

**Comment by XayahSuSuSu** [comment]
Plz provide the version of the app and the screenshot of DataBackup folder in ur new phone

**Comment by digirus808** [comment]
Version 1.01 alpha01
![PXL_20230627_151540114](https://github.com/XayahSuSuSu/Android-DataBackup/assets/97450197/6f1400c0-b37c-461f-8deb-52a495c6f9c8)

Here's how I restored in the new phone

**Comment by XayahSuSuSu** [comment]
> Version 1.01 alpha01 ![PXL_20230627_151540114](https://user-images.githubusercontent.com/97450197/249163958-6f1400c0-b37c-461f-8deb-52a495c6f9c8.jpg)
> 
> Here's how I restored in the new phone

Looks normal.
Can u show ur backup directory item in settings, and is the restore list empty?

**Comment by digirus808** [comment]
Here's to see that it's not empty. 27gb. And proof that I have content in the folders. 
![PXL_20230627_154134502](https://github.com/XayahSuSuSu/Android-DataBackup/assets/97450197/63f79885-415d-421f-bcd9-c4194e830888)

![PXL_20230627_154202009](https://github.com/XayahSuSuSu/Android-DataBackup/assets/97450197/0debceed-c4aa-40c8-a206-be12cf841058)
![PXL_20230627_154155155](https://github.com/XayahSuSuSu/Android-DataBackup/assets/97450197/0c60c98f-7a8c-46b7-96ee-dadea9840568)

**Comment by XayahSuSuSu** [comment]
> Here's to see that it's not empty. 27gb. And proof that I have content in the folders. ![PXL_20230627_154134502](https://user-images.githubusercontent.com/97450197/249171645-63f79885-415d-421f-bcd9-c4194e830888.jpg)
> 
> ![PXL_20230627_154202009](https://user-images.githubusercontent.com/97450197/249171384-0debceed-c4aa-40c8-a206-be12cf841058.jpg) ![PXL_20230627_154155155](https://user-images.githubusercontent.com/97450197/249171393-0c60c98f-7a8c-46b7-96ee-dadea9840568.jpg)

I mean in app

**Comment by XayahSuSuSu** [comment]
No response, close for now
