### ISSUE TITLE
[Feature] Add Counter

### ISSUE THREAD

**Issue by Mahantor** [XayahSuSuSu/Android-DataBackup#134]
**Describe the feature**
A clear and concise description.

Please add a counter for the restore and backup section
The number 2 indicates the number of selected apps and 168 indicates the number of available apps
![Screenshot_2023-06-29-19-54-21-328_com.xayah.databackup-edit.jpg](https://github.com/XayahSuSuSu/Android-DataBackup/assets/91434001/8e66da04-7e25-4272-a292-da453774ab14)

**Comment by XayahSuSuSu** [comment]
Added in **1.1.0-alpha01**

**Comment by Mahantor** [comment]
Please add the total number of apps or the number of unselected apps as in the screenshot
