### ISSUE TITLE
[Bug] Thnox双开恢复后的应用软重启

### ISSUE THREAD

**Issue by Goojoe** [XayahSuSuSu/Android-DataBackup#135]
**Describe the bug**
不知道是哪边的问题

**To Reproduce**
1. 打开Thanox的双开功能
2. 重启
3. 恢复数据
4. 打开双开应用,系统100%软重启

**Expected behavior**

**Screenshots**
![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/78355492/440623d9-b50b-4713-a45e-95e5055eb5d9)

**Smartphone (please complete the following information):**
 - Device: Motorola edge x30
 - OS: MYUI5.0 Android 13
 - Version App 1.0.1-alpha01

**Additional context**

**Comment by XayahSuSuSu** [comment]
清除应用数据再打开就不会？

**Comment by Goojoe** [comment]
我试了下,可能是一个系统BUG,没用数据备份APP,开启双开后依然会重启,我先Thanox反馈一下,之后在找你试试
