### ISSUE TITLE
为啥自定义添加的文件夹会自动清除

### ISSUE THREAD

**Issue by xushet** [XayahSuSuSu/Android-DataBackup#137]
![Screenshot_20230711-090922_数据备份.png](https://github.com/XayahSuSuSu/Android-DataBackup/assets/34502902/32aca0c0-9b57-42e4-ba02-25af0c6221ba)
我手动添加了一些备份路径，备份一次后再打开app就消失了，又要手动添加

**Comment by xushet** [comment]
![Screenshot_20230711-220458_数据备份.png](https://github.com/XayahSuSuSu/Android-DataBackup/assets/34502902/ddaea400-153c-4402-9e3d-5985c65fcad4)

而且备份完成后也无法恢复

**Comment by XayahSuSuSu** [comment]
应该是1.0.1-alpha01的bug，试试sp1或等待修复
