### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Mahantor** [XayahSuSuSu/Android-DataBackup#138]
**Describe the bug**
I encountered this error while loading apps for re-store

**To Reproduce**
1. Go to setting
2. Click on backup directory
3. Select backup location » I selected microSD card (/storage/4672-1E0D/DataBackup/)
4. When loading apps for restore
5. I get error page and save log

**Expected behavior**
The backup files are healthy and there is full root access.  Restore should be done without error

**Screenshots**
![Screenshot_2023-07-11-13-34-22-697_com.xayah.databackup.jpg](https://github.com/XayahSuSuSu/Android-DataBackup/assets/91434001/211d7428-037f-43a8-a4b6-b08082df4d99)

I even have a problem to take backup in this file path
![Screenshot_2023-07-11-13-32-35-965_com.xayah.databackup.jpg](https://github.com/XayahSuSuSu/Android-DataBackup/assets/91434001/7d6603c9-d834-4c75-a1ac-b96ec244f94e)

**Smartphone (please complete the following information):**
 - Device: [Redmi note 9 pro]
 - OS: [e.g. MIUI14, Android12]
 - Version [e.g. stable 14.0.3]

**Additional context**

I installed DataBackup-1.0.0 version and managed to restore. Please solve this problem in the next version.

Error log :
![Screenshot_2023-07-11-20-54-24-244_com.xayah.databackup.jpg](https://github.com/XayahSuSuSu/Android-DataBackup/assets/91434001/46fee6ca-31cf-4deb-9b13-0a27d4ef16ee)

**Comment by XayahSuSuSu** [comment]
Should be fixed in https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/1.1.0-alpha02
Can you have a try?
