### ISSUE TITLE
[Bug] 恢复界面选择文件夹后恢复失败

### ISSUE THREAD

**Issue by FrankHB** [XayahSuSuSu/Android-DataBackup#14]
恢复界面选择文件夹（我就测了 `/storage/emulated/0/Download` ）后恢复，恢复完成的主界面虽然显示√的图标但是实际全都恢复失败，日志中显示无法访问 `decompress` 和 `install_apk` 等 shell 函数（`inaccessible or not found`）。显然 shell 环境不正常。

偶尔还会“请退出搜索模式”的提示，不过没确定怎么重现（这个自动退出可以么）。

**Comment by FrankHB** [comment]
备份文件移动回去默认目录可以恢复。

**Comment by XayahSuSuSu** [comment]
我这边尝试复现没有成功，根据你的描述是因为bashrc没有加载成功，但按理说Shell环境不正常启动时bashrc会显示×

**Comment by XayahSuSuSu** [comment]
退出搜索模式复现成功
