### ISSUE TITLE
[Bug] Need lot time to load list app

### ISSUE THREAD

**Issue by kyzsuukii** [XayahSuSuSu/Android-DataBackup#140]
**Describe the bug**

when try backup app and load list app its need lot time to load (5-10 minute)

**To Reproduce**
1. Click Backup 

**Expected behavior**
fast load

**Screenshots**
![Screenshot_20230718-201436_DataBackup.png](https://github.com/XayahSuSuSu/Android-DataBackup/assets/110718021/d1c991b5-d3d2-481e-89b6-dbf87f34d044)

**Smartphone (please complete the following information):**
 - Device: Redmi Note 7
 - OS: EvolutionX, Android 13
 - Version 1.0.1-alpha01

**Additional context**
-

**Comment by XayahSuSuSu** [comment]
Yeah will optimize it in next version

**Comment by XayahSuSuSu** [comment]
Check in https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/1.1.0-alpha02
