### ISSUE TITLE
[Bug] 应用发生崩溃 (RootService is null）

### ISSUE THREAD

**Issue by Rilomilo** [XayahSuSuSu/Android-DataBackup#144]
**重现方法**
进入应用备份菜单，选择任意应用，点击下一步按钮后崩溃。
或者点击应用恢复菜单，然后直接崩溃。

**设备信息**
- 小米8
- MIUI11，Android9
- Magisk 25210，已永久授予root权限

**下面是截图**
（在应用发生崩溃界面点击保存按钮，无论选择什么目录都会保存失败）
![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/30747107/40ffd785-f263-4124-aea6-84261ee924b6)
![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/30747107/aff82d8a-d20f-4aa7-8ff2-1dd3894c61e4)

**Comment by XayahSuSuSu** [comment]
1.0.1-alpha01已知问题
由于下个版本完全重构，可能不会对此版本针对性修复
