### ISSUE TITLE
[Bug] 类原生安卓13备份的数据在miui安卓12上面恢复时出现中文编码错误

### ISSUE THREAD

**Issue by ubadly** [XayahSuSuSu/Android-DataBackup#147]
**Describe the bug**
[Bug] 类原生安卓13备份的数据在miui安卓12上面恢复时会因为【覆盖】文件夹导致出现中文编码错误
![Screenshot_2023-08-29-15-06-15-707_com xayah databackup](https://github.com/XayahSuSuSu/Android-DataBackup/assets/28584937/f86b0616-9ddb-48d3-9446-493fd699fd66)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi 10 Ultra]
 - OS: [e.g. MIUI14, Android13]
 - Version [e.g. Beta-4.3.7]

**Additional context**

**Comment by XayahSuSuSu** [comment]
把覆盖改成任意英文或数字字符可以正常恢复吗

**Comment by ubadly** [comment]
> 把覆盖改成任意英文或数字字符可以正常恢复吗

貌似可以，但现在无法安装软件，提示 apk not instalkled

**Comment by ubadly** [comment]
我已经打开了允许这个软件安装软件的权限，但应该跟这个没有关系

**Comment by XayahSuSuSu** [comment]
> > 把覆盖改成任意英文或数字字符可以正常恢复吗
> 
> 貌似可以，但现在无法安装软件，提示 apk not instalkled

看界面貌似没有选择恢复APK吧，你没有备份APK吗，可以去备份目录检查下

**Comment by xushet** [comment]
使用1.1.0也出现了这个问题，备份到中文名的文件夹可以，但是恢复时就失败，把文件夹名改成默认的备份文件夹名称就恢复成功了

**Comment by XayahSuSuSu** [comment]
> 使用1.1.0也出现了这个问题，备份到中文名的文件夹可以，但是恢复时就失败，把文件夹名改成默认的备份文件夹名称就恢复成功了

可以提供下日志吗？
