### ISSUE TITLE
不能直接备份到u盘吗？

### ISSUE THREAD

**Issue by mrlihx** [XayahSuSuSu/Android-DataBackup#148]
![Screenshot_2023-09-02-15-05-37-561_com.xayah.databackup.jpg](https://github.com/XayahSuSuSu/Android-DataBackup/assets/68861286/2b4f9932-cdf9-4cee-8a13-92a41e0e596c)

**Comment by XayahSuSuSu** [comment]
请格式化为以下其中一种形式
![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/44322170/38bd49c0-7cb8-4575-a81a-12f436fc1ef4)
