### ISSUE TITLE
[Feature]  Multicore/thread for compression of backups

### ISSUE THREAD

**Issue by Tokito-Kun** [XayahSuSuSu/Android-DataBackup#151]
Use multicore/thread for compression of archives 
While backing up large files like genshin 27Gb it takes lot of time , zstd does support it

**Comment by XayahSuSuSu** [comment]
It has already been multi-thread.
The compression command is something like this:
`tar --totals -cpf /storage/emulated/0/DataBackup/archives/packages/com.coolapk.market/1695621773088/user.tar.zst -C "/data/user/0" "com.coolapk.market" -I "zstd -r -T0 --ultra -1 -q --priority=rt"`
