### ISSUE TITLE
[Bug] 无法获得Root权限

### ISSUE THREAD

**Issue by Goojoe** [XayahSuSuSu/Android-DataBackup#153]
![Screenshot_2023-09-27-14-49-01-273_com topjohnwu magisk-edit](https://github.com/XayahSuSuSu/Android-DataBackup/assets/78355492/8ca56bae-31e3-48c2-99d1-1ef670d0b94d)

**Smartphone (please complete the following information):**
 - Device: MotorolaEdgeX30
 - OS: MIUI14 Android 13
 - Version 1.1.0-alpha01
 - Magisk 26.3

**Additional context**

**Comment by Goojoe** [comment]
![Screenshot_2023-09-27-14-51-19-331_com xayah databackup foss-edit](https://github.com/XayahSuSuSu/Android-DataBackup/assets/78355492/325c4276-4766-481f-b0e0-db29fcccbf29)

**Comment by Goojoe** [comment]
搞错了，上面Magisk界面的是之前1.0.1版本的，1.1.0版本Magisk Root管理不会显示，也无法授权

**Comment by franco27** [comment]
A rooted phone is required for your application?

**Comment by Goojoe** [comment]
Yes,this application need rooted phone

**Comment by XayahSuSuSu** [comment]
奇怪了，试过重启或者重装magisk吗

**Comment by Goojoe** [comment]
重启了，没用，重装Magisk没试

**Comment by XayahSuSuSu** [comment]
> 重启了，没用，重装Magisk没试

简直玄学，这一块的代码几乎没动(

**Comment by melxman** [comment]
但是前一个版本的获取权限是没问题的😳

**Comment by XayahSuSuSu** [comment]
> 但是前一个版本的获取权限是没问题的😳

你也是这个版本弹不出授权窗口吗

**Comment by Goojoe** [comment]
不行

**Comment by melxman** [comment]
> > 但是前一个版本的获取权限是没问题的😳
> 
> 你也是这个版本弹不出授权窗口吗

对的

**Comment by Goojoe** [comment]
我另一个平板版本是Magisk 26.1可以打开

**Comment by XayahSuSuSu** [comment]
> 不行

这个呢
[DataBackup-1.1.0-alpha01-arm64-v8a-premium-release.zip](https://github.com/XayahSuSuSu/Android-DataBackup/files/12740246/DataBackup-1.1.0-alpha01-arm64-v8a-premium-release.zip)

**Comment by Goojoe** [comment]
还是不行

**Comment by XayahSuSuSu** [comment]
嘶，难搞，我这边26.3也没有问题

**Comment by XayahSuSuSu** [comment]
你那边有装shamiko吗

**Comment by Goojoe** [comment]
装了

**Comment by Goojoe** [comment]
想起来了，喔之前开了Shamiko白名单，现在好了....
媒体和通讯点击无效

**Comment by XayahSuSuSu** [comment]
目前只重构完应用数据的备份恢复功能
