### ISSUE TITLE
Crash while loading the Apps list

### ISSUE THREAD

**Issue by msalah-kw** [XayahSuSuSu/Android-DataBackup#154]
![Screenshot_20230927_194755_DataBackup.jpg](https://github.com/XayahSuSuSu/Android-DataBackup/assets/132661669/72f30db0-2e47-4d6e-b77f-2693a27cd7ef)

**Comment by XayahSuSuSu** [comment]
Fixed in https://github.com/XayahSuSuSu/Android-DataBackup/commit/45698962b7a461c1c5f5d08814d98b5c87418382
Plz wait for the next build
