### ISSUE TITLE
Unable to Restore!!

### ISSUE THREAD

**Issue by Hansraj76** [XayahSuSuSu/Android-DataBackup#155]
I used latest version of data backup. When i am trying to restore apps no apps are showing in restore tab. But when i checked file manager then i found there are packages available but they aren't showing. I tried older version also. Still Same. Please help me to recover data and apps.
![Screenshot_2023-09-28-16-15-30-80_55bef12f624c2b805189a6aa783c400d](https://github.com/XayahSuSuSu/Android-DataBackup/assets/106469343/cc5755d9-b93b-47f0-8d48-6f5b26e67847)
![Screenshot_2023-09-28-16-15-42-88_55bef12f624c2b805189a6aa783c400d](https://github.com/XayahSuSuSu/Android-DataBackup/assets/106469343/cc7dc654-97b6-4bda-899e-44f0cadec473)
![Screenshot_2023-09-28-16-16-24-36](https://github.com/XayahSuSuSu/Android-DataBackup/assets/106469343/9611af5f-f72d-49d6-a673-9ecf17246c1e)
![Screenshot_2023-09-28-16-16-48-71](https://github.com/XayahSuSuSu/Android-DataBackup/assets/106469343/3c51b9c9-677b-4f3b-a543-28507bff624a)

**Comment by XayahSuSuSu** [comment]
Click the `reload` button in resore page

**Comment by Hansraj76** [comment]
That X icon in buttom?

**Comment by XayahSuSuSu** [comment]
![IMG_20230928_191158](https://github.com/XayahSuSuSu/Android-DataBackup/assets/44322170/86f11f4b-fe92-44f3-9c59-c58051f3150b)

**Comment by Hansraj76** [comment]
Thank You Soo Much Sir. Issue Fixed. Love Your App.

**Comment by XayahSuSuSu** [comment]
Glad to help:)
