### ISSUE TITLE
[Feature] 自定义目录为啥要取消啊？

### ISSUE THREAD

**Issue by listky** [XayahSuSuSu/Android-DataBackup#156]
自定义目录非常实用，对于我这种经常格式化data的人来说，备份到otg的u盘或者虚拟分区，太关键了啊，之前看到有swift的高级版一直不想用，就是因为它没有自定义目录，为啥要取消啊，如果是为了建设后续的云端备份，那可以提供二选一的开关吗？感谢

**Comment by XayahSuSuSu** [comment]
没有取消，只是暂时还没做

**Comment by XayahSuSuSu** [comment]
4b262c58a547d1ef9fc6aa437390630c0330cf70

**Comment by XayahSuSuSu** [comment]
> 所以vfat的内存卡不支持也是还没做吗？

vfat是32位文件系统，所以不是不做而是不会支持

**Comment by XayahSuSuSu** [comment]
https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/1.1.0-alpha03
