### ISSUE TITLE
[Bug] unable to select sd card
1.1.0-alpha02

### ISSUE THREAD

**Issue by Mahantor** [XayahSuSuSu/Android-DataBackup#157]
**Describe the bug**

I can't select the sd card

**Screenshots**
![Screenshot_2023-10-02-19-25-59-729_com.xayah.databackup.premium-edit.jpg](https://github.com/XayahSuSuSu/Android-DataBackup/assets/91434001/b892b109-3439-44b3-a5d8-f4aa4dc827b4)

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi Redmi note 9 pro]
 - OS: [e.g. MIUI14, Android12]

**Comment by XayahSuSuSu** [comment]
`vfat` is not supported, here are all supported formats:
![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/44322170/20c4ee70-74a8-4fea-899e-880aeb5244c3)

**Comment by Mahantor** [comment]
Version 1.0.1-alpha01 (97) supports this format, please add this format to the new version.

**Comment by Mahantor** [comment]
Version 1.0.1-alpha01 (97) supports this format, please add this format to the new version.
![Screenshot_2023-10-04-08-50-35-678_com.xayah.databackup-edit.jpg](https://github.com/XayahSuSuSu/Android-DataBackup/assets/91434001/7bf0bf86-9693-45d0-bf88-5aa22d169e0a)

**Comment by XayahSuSuSu** [comment]
> Version 1.0.1-alpha01 (97) supports this format, please add this format to the new version. ![Screenshot_2023-10-04-08-50-35-678_com.xayah.databackup-edit.jpg](https://user-images.githubusercontent.com/91434001/272469484-7bf0bf86-9693-45d0-bf88-5aa22d169e0a.jpg)

1. [1.0.1-alpha01](https://github.com/XayahSuSuSu/Android-DataBackup/blob/0e16a8fe624c3989c0b9a00a863e9ac554a3e86f/app/src/main/java/com/xayah/databackup/ui/activity/settings/components/content/App.kt#L210) didn't support `vfat`, either.
2. `vfat` is 32bit fs which means it **DOES NOT** support files larger than 4GB, it's **DANGEROUS** for backup, so we won't add it officially.
3. You can still select this path manually anyway.
