### ISSUE TITLE
恢复备份前需要先安装对应app吗？需要先启动一次吗？

### ISSUE THREAD

**Issue by Lovefish** [XayahSuSuSu/Android-DataBackup#158]
1 备份的时候选择备份apk和数据，恢复的时候需要先安装对应的APP吗？还有是否需要先启动这个APP，再继续恢复？（启动还是不启动APP再恢复会有区别吗？）
2 只备份微信的数据，然后直接再新手机上安装微信再恢复数据过去，这样的话，能够保持微信在登录状态吗？

**Comment by XayahSuSuSu** [comment]
不需要，另外我建议你先找几个APP亲自试试
