### ISSUE TITLE
[Bug] cannot restore

### ISSUE THREAD

**Issue by Pratham-Malhotra** [XayahSuSuSu/Android-DataBackup#159]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi 10 Ultra]
 - OS: [e.g. MIUI14, Android13]
 - Version [e.g. Beta-4.3.7]

**Additional context**

**Comment by XayahSuSuSu** [comment]
What error? Any screenshots or logs?
