### ISSUE TITLE
Backup and restore [Bug] 

### ISSUE THREAD

**Issue by Pratham-Malhotra** [XayahSuSuSu/Android-DataBackup#160]
**Describe the bug**
First it keep failing at backup if it takes backup restore list doesn't work.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Poco F4]
 - OS: [e.g. Custom Roms]
 - Version [e.g. Beta-4.3.7]

**Additional context**
`
![Screenshot_20231007-184351_Files by Google](https://github.com/XayahSuSuSu/Android-DataBackup/assets/144879877/0ac8fcee-44e1-4936-927f-0039d97a3b0e)
![Uploading Screenshot_20231007-184331_DataBackup.png…]()
`

**Comment by XayahSuSuSu** [comment]
However, I can't see any errors from this screenshot.
Can you give it a detailed description?

**Comment by XayahSuSuSu** [comment]
So have you backed up via `Beta-4.3.7` and now it can't restore correctly?
Or you wanna back up but this version failed.

**Comment by Mahantor** [comment]
I have same problem with version 1.1.0 alpha04
Backup not working in this version

![Screenshot_2023-10-07-17-51-57-366_com.miui.securitycenter-edit.jpg](https://github.com/XayahSuSuSu/Android-DataBackup/assets/91434001/7a1acf45-5368-4c38-b9de-f7ab9763a6a2)


https://file.io/IHB5bR2DKBim

**Comment by XayahSuSuSu** [comment]
> I have same problem with version 1.1.0 alpha04 Backup not working in this version
> 
> ![Screenshot_2023-10-07-17-51-57-366_com.miui.securitycenter-edit.jpg](https://user-images.githubusercontent.com/91434001/273391548-7a1acf45-5368-4c38-b9de-f7ab9763a6a2.jpg)
> 
> ![Screenshot_2023-10-07-17-31-05-896_com.xayah.databackup.premium.jpg](https://user-images.githubusercontent.com/91434001/273391604-fb96ab63-c03b-4236-bb64-3b5aa6b4dc35.jpg)
> 
> https://file.io/IHB5bR2DKBim

You installed the wrong abi version.
Download `armv8` version

**Comment by Pratham-Malhotra** [comment]
![Screenshot_20231008-144102_DataBackup.png](https://github.com/XayahSuSuSu/Android-DataBackup/assets/144879877/7fdd7105-85ad-4aa8-acea-6fc2af261349)

Any version 7a 8a premium foss whatever, when we take backup first it shows some error backing up failed, IDK after some try it take backup since I use custom roms I have to switch to another and I backup it's backup folder to external drive, when I take/recognise back that data backup folder to my device it doesn't take folder even after root and storage access given, alternative I am using old version this problem is in all latest version.

**Comment by XayahSuSuSu** [comment]
> ![Screenshot_20231008-144102_DataBackup.png](https://user-images.githubusercontent.com/144879877/273438415-7fdd7105-85ad-4aa8-acea-6fc2af261349.png)
> 
> Any version 7a 8a premium foss whatever, when we take backup first it shows some error backing up failed, IDK after some try it take backup since I use custom roms I have to switch to another and I backup it's backup folder to external drive, when I take/recognise back that data backup folder to my device it doesn't take folder even after root and storage access given, alternative I am using old version this problem is in all latest version.

1. If you used the `1.1.0-alphaX` for backup, you need to click `Reload` button in `Restore` page.
2. You said you met some errors but I need a detailed info for that to fix them.
3. Can you click `Structure` button in `Backup` page and give me a screenshot?

**Comment by Pratham-Malhotra** [comment]
Thank you man in previous version when we but data backup folder in device app automatically detects but in latest ones as you said you have to click reload button to make data backup detects data backup folder, yes after clicking reload it automatically takes it's folder, is not possible it will automically take data backup folder without clicking reload button like previous version. 😊🫶🙏

**Comment by Pratham-Malhotra** [comment]
> Thank you man in previous version when we but data backup folder in device app automatically detects but in latest ones as you said you have to click reload button to make data backup detects data backup folder, yes after clicking reload it automatically takes it's folder, is not possible it will automically take data backup folder without clicking reload button like previous version. 😊🫶🙏

This app is best from all other apps available in market, you can close this issue as i know solution to my problem thank you.

**Comment by XayahSuSuSu** [comment]
> Thank you man in previous version when we but data backup folder in device app automatically detects but in latest ones as you said you have to click reload button to make data backup detects data backup folder, yes after clicking reload it automatically takes it's folder, is not possible it will automically take data backup folder without clicking reload button like previous version. 😊🫶🙏

Automatically reloading is possible but it will slow the list loading down every time you enter in it.

**Comment by XayahSuSuSu** [comment]
> > Thank you man in previous version when we but data backup folder in device app automatically detects but in latest ones as you said you have to click reload button to make data backup detects data backup folder, yes after clicking reload it automatically takes it's folder, is not possible it will automically take data backup folder without clicking reload button like previous version. 😊🫶🙏
> 
> This app is best from all other apps available in market, you can close this issue as i know solution to my problem thank you.

Thanks bro:)
