### ISSUE TITLE
[Feature] 将一个或多个app数据通过压缩为单个文件直接发送/恢复

### ISSUE THREAD

**Issue by Goojoe** [XayahSuSuSu/Android-DataBackup#162]
在一台手机设置好app的参数后直接备份发送给另一台手机，减少重复操作

**Comment by XayahSuSuSu** [comment]
啥意思，怎么发送，压缩哪些为单个文件

**Comment by Goojoe** [comment]
就是app数据啊 apk 内部数据 obb啥的直接打包为压缩包发送

**Comment by XayahSuSuSu** [comment]
apk user obb等数据打包成一个压缩包
意思是还要写新的恢复方案？
我不是特别理解这个功能的优越性
和直接打包DataBackup有啥区别

**Comment by Goojoe** [comment]
好吧，你说的对，我手动打包也是一样的
