### ISSUE TITLE
[Bug] ‎Databackup does not follow the symlink of the data folder

### ISSUE THREAD

**Issue by ZhymabekRoman** [XayahSuSuSu/Android-DataBackup#164]
**Describe the bug**
‎Databackup does not follow the symlink of the data folder. For example I store Termux application data in second partition of SD card to reduce internal EMMC degradation. To do that I just make symlink /data/data/com.termux to external card folder.

**To Reproduce**
1. Go to 'Databackup'
2. Select application to backup
3. Start backup
4. See that data is too small size

**Expected behavior**
Properly saved data folder of application

**Smartphone (please complete the following information):**
 - Device: Redmo 10C
 - OS:  MIUI13, Android12
 - Version: 1.1.0-alpha04

**Comment by XayahSuSuSu** [comment]
Consider to add `-h` parameter in backup cmds

**Comment by ZhymabekRoman** [comment]
> Consider to add `-h` parameter in backup cmds

How can I do that in DataBackup options?

**Comment by XayahSuSuSu** [comment]
> > Consider to add `-h` parameter in backup cmds
> 
> How can I do that in DataBackup options?

I will implement it in settings.

**Comment by XayahSuSuSu** [comment]
Can you give it a try?
Switch on **Follow symbols** in the settings first.
[DataBackup-1.1.0-alpha04-arm64-v8a-foss-release.zip](https://github.com/XayahSuSuSu/Android-DataBackup/files/13063266/DataBackup-1.1.0-alpha04-arm64-v8a-foss-release.zip)

**Comment by ZhymabekRoman** [comment]
Thanks @XayahSuSuSu, seems like backup works perfectly. But there some problem:
1. After restoring from backup, Termux says that there some permission error problem. I don't known what was a problem. I tried to test restore from same backup by fresh installing Termux without any linking data folder into external SD card and there's no permissions problem.
2. After restore I checked data folder and released that after restoring, data folder wasn't linked to external SD card folder as I created backup, instead it was in internal memory
 
I don't known, can we says that it's bug, because DataBackup doesn't designed to handle such non common things. But anyway thanks for this functionality, if you see that this is bug of DataBackup I will appreciate if you fix that. For now I have some ideas to create FOS tool that will manage applications data transformation to internal and external card with and without root access.

And there some problem in Russian translation, very hard to understand whole things. If I have some time, I will try fix them.

**Comment by XayahSuSuSu** [comment]
> 1. After restoring from backup, Termux says that there some permission error problem. I don't known what was a problem. I tried to test restore from same backup by fresh installing Termux without any linking data folder into external SD card and there's no permissions problem.

I tested termux backup/restoring, it works fine on my phone, so I think it may relate to the linking

**Comment by ZhymabekRoman** [comment]
Okay, thanks, I close this issue since problem is solved

**Comment by XayahSuSuSu** [comment]
> 2. I checked data folder and released that after restoring, data folder wasn't linked to external SD card folder as before backup, instead it was in internal memory

This is not easy to implement in app and I think it goes beyond the features of the app.
