### ISSUE TITLE
[Feature] Readdition of previously available features

### ISSUE THREAD

**Issue by mackdroid** [XayahSuSuSu/Android-DataBackup#167]
**Describe the feature**
- Missing Select all while backing up and restoring
- Wierd unsupported filesystem error when i can just manually add the path to my sdcard and it just works
- text clipping on restore screen
![Screenshot_20231025-104358](https://github.com/XayahSuSuSu/Android-DataBackup/assets/68280146/8991183a-ca43-408b-a917-6aba31c08a86)
and the buttons for backing up apps and media is so small for an app whose purpose is to backup apps, UX honestly went downhill

**Comment by XayahSuSuSu** [comment]
> Missing Select all while backing up and restoring

Long click the card and you will see it.

> Wierd unsupported filesystem error when i can just manually add the path to my sdcard and it just works

It will detect the fs format and report errors if the target is 32bit fs, which doesn't suppprt files bigger than 4gb.

> and the buttons for backing up apps and media is so small for an app whose purpose is to backup apps, UX honestly went downhill

It will get optimized after all wip features being implemented. The UX is indeed in a mess now.
