### ISSUE TITLE
删除所选-描述歧义

### ISSUE THREAD

**Issue by Goojoe** [XayahSuSuSu/Android-DataBackup#169]
我刚才还以为是取消已选择的应用，没想到把数据给删了，还好数据不重要

应该修改描述，警告用户这是删除用户数据且不可恢复

**Comment by XayahSuSuSu** [comment]
是指这个？
![Screenshot_2023-11-03-00-09-41-271_com xayah data](https://github.com/XayahSuSuSu/Android-DataBackup/assets/44322170/2a8beee8-9c68-4ba9-99dc-d95cd061cf7e)

**Comment by Goojoe** [comment]
![Screenshot_2023-11-03-00-16-49-51_0a93f116ed23bd66387c50019ff4fafe](https://github.com/XayahSuSuSu/Android-DataBackup/assets/78355492/b995f0ee-b8f3-4492-afb0-6c748370e54a)
这个

**Comment by Goojoe** [comment]
还有，只备份应用数据的时候，没备份应用名
![Screenshot_2023-11-03-00-20-16-13_0a93f116ed23bd66387c50019ff4fafe](https://github.com/XayahSuSuSu/Android-DataBackup/assets/78355492/33c3598d-cbe0-4f77-85c2-7da417008b81)

**Comment by XayahSuSuSu** [comment]
了解了

**Comment by xushet** [comment]
看一眼真是心脏骤停😅
