### ISSUE TITLE
[Bug] 1.0.1-alpha04数组越界崩溃

### ISSUE THREAD

**Issue by ftevxk** [XayahSuSuSu/Android-DataBackup#170]
![Uploading Screenshot_2023-11-05-15-17-33-127_com.xayah.databackup.jpg…]()

**Comment by ftevxk** [comment]
旧数据问题

**Comment by XayahSuSuSu** [comment]
是Compose相关的bug，不过你说的旧数据问题是什么意思

**Comment by ftevxk** [comment]
之前安装了1.1.0-alpha04，安装1.0.1-alpha04后把1.1.0的卸载后忘记把备份的文件夹删除了

**Comment by XayahSuSuSu** [comment]
Fatal Exception: java.lang.IndexOutOfBoundsException
是这个崩溃吗，我从来没有成功复现过，但在Firebase中能看到有不低的崩溃率。
请问你那边能稳定复现这个bug吗

**Comment by ftevxk** [comment]
没有再复现过了
