### ISSUE TITLE
[Bug] Unable to Restore Backup

### ISSUE THREAD

**Issue by Hansraj76** [XayahSuSuSu/Android-DataBackup#174]
I backup my apps and data using 1.1.0 alpha1. But when i tried to restore it. App gets automatically crashed. So i thought that it because of old version maybe but when i install latest version there is nothing to restore. Help me get out of this situation.

**Comment by XayahSuSuSu** [comment]
Install [1.1.0-alpha04](https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/1.1.0-alpha04) then click reload btn

**Comment by Hansraj76** [comment]
You always being my lifesaver. But icons are not visible of apps but there packages are showing. So i can say it is fixed right now. Can i change my app version after restoring data.

**Comment by XayahSuSuSu** [comment]
> You always being my lifesaver. But icons are not visible of apps but there packages are showing. So i can say it is fixed right now. Can i change my app version after restoring data for next time restore.

Yes you can change to 1.1.0-alpha04 next time, the icon problem will be solved.
