### ISSUE TITLE
[Tutorial | 教程] AList挂载Webdav本地存储 使用云端连接备份教程

### ISSUE THREAD

**Issue by Goojoe** [XayahSuSuSu/Android-DataBackup#177]
## Alist设置
> 怎么安装Alist就不说了，看官方文档 https://alist.nn.ci/zh/guide/install/manual.html

1. 添加本地存储
![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/78355492/19493482-9cb7-453f-b7aa-731bb271d979)
**这里的挂载路径会在首页显示**
---
2. 滚动到下面填写你需要在Windows上存储的文件夹，在Alist填写这个文件并添加
![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/78355492/5db83376-edb4-403d-8e4d-fe9008452cc1)

3. 在你上面Alist填写的**根文件夹路径**内再创建一个文件夹，这会成为数据备份APP的远程路径
![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/78355492/f4ee1413-0472-4f9e-afe4-17825593c205)

## 数据备份APP设置
添加webdav存储
填写方式如下
- 名字：随意
- 主机：http(s)://Windows主机IP:Alist端口/dav
- Alist账号
- Alist密码
> 更多可参考官方文档 https://alist.nn.ci/zh/guide/webdav.html

![Screenshot_20231206-215413_数据备份](https://github.com/XayahSuSuSu/Android-DataBackup/assets/78355492/9ef91024-2f18-4e74-9c00-340d1093b168)

返回点击右下角的账户，设置远程→选择你挂载的目录的子目录即可，返回测试连接，没有问题后
点击账户左边的九宫格备份即可

**Comment by tyjavajar** [comment]
云端中断了后，继续只能从头再来，不能跳过已备份 :(

**Comment by sm0012333** [comment]
按这个来的，备份都报错。

**Comment by sm0012333** [comment]
> 按这个来的，备份都报错。

备份失败：reqwest_dav:Error{kind
"Decode",source:Server(ServerError{
response_code:405,exception:"server
exception and parse error",message:
"Method Not Allowed"})}

**Comment by chenghui03** [comment]
> > 按这个来的，备份都报错。
> 
> 备份失败：reqwest_dav:Error{kind "Decode",source:Server(ServerError{ response_code:405,exception:"server exception and parse error",message: "Method Not Allowed"})}

请你参考这个教程[alist webdav](alist.nn.ci/zh/guide/webdav.html)
这可能是因为管理权限的问题，你可以在用户管理看使用的账户是否有webdav管理权限
