### ISSUE TITLE
[Bug] Stuck during backup

### ISSUE THREAD

**Issue by Mahantor** [XayahSuSuSu/Android-DataBackup#178]
**Describe the bug**

Thank you for your efforts, the app's ui has become very beautiful and functional, but I encountered two problems

1 - Backup operation stuck while backing up
(I will upload the log app for you)

2- In your opinion, it is better not to hide not selected apps

**Expected behavior**

**Screenshots**
Log
![log_1702193536766.txt](https://github.com/XayahSuSuSu/Android-DataBackup/files/13628454/log_1702193536766.txt)

Screen record for item #2
https://github.com/XayahSuSuSu/Android-DataBackup/assets/91434001/e205a3cc-ecca-4ced-948e-5a0434f4ae5c

**Smartphone

 - Device: [Redmi note 9 pro]
 - OS: [MIUI14, Android12]
 - Version [Miui 14.0.3]

**Comment by XayahSuSuSu** [comment]
1. It seems trying to kill **com.xayah.databackup**, can you test backing up it separately and see if it gets stuck?
```
2023-12-10 11:11:02.324    PackagesBackupServiceImpl    Current package: com.xayah.databackup, apk: true, data: true.
2023-12-10 11:11:02.325    PackagesBackupServiceImpl    Trying to kill com.xayah.databackup.
```

2. It doesn't get hidden, it just jumps to the bottom.

**Comment by Mahantor** [comment]
I ran into this problem again
[log_1702231483001.txt](https://github.com/XayahSuSuSu/Android-DataBackup/files/13628816/log_1702231483001.txt)

**Comment by XayahSuSuSu** [comment]
> Can reproduce this on OnePlus 7 Pro Hydrogen OS 9.5.6.GM21 (Android 9).
> 
> ```
> 2023-12-11 15:09:56.288    PackagesBackupServiceImpl    Current package: com.android.chrome, apk: true, data: true.
> 2023-12-11 15:09:56.288    PackagesBackupServiceImpl    Trying to kill com.android.chrome.
> 2023-12-11 15:19:42.638    SHELL_IN      ps -A | grep -w tar | grep -w root | awk 'NF>1{print $2}' | xargs kill -9
> 2023-12-11 15:19:42.638    SHELL_OUT     kill: missing argument (see "kill --help")
> 2023-12-11 15:19:42.638    SHELL_CODE    1
> ```

Yeah I found the issue.

**Comment by XayahSuSuSu** [comment]
@shniubobo @Mahantor 
Can you have a test for it ?

[DataBackup-1.1.0-alpha05-arm64-v8a-foss-release.zip](https://github.com/XayahSuSuSu/Android-DataBackup/files/13637700/DataBackup-1.1.0-alpha05-arm64-v8a-foss-release.zip)

**Comment by Mahantor** [comment]
> @shniubobo @Mahantor 
> Can you have a test for it ?
> 
> [DataBackup-1.1.0-alpha05-arm64-v8a-foss-release.zip](https://github.com/XayahSuSuSu/Android-DataBackup/files/13637700/DataBackup-1.1.0-alpha05-arm64-v8a-foss-release.zip)

Thank you, all apps were backed up correctly
I will test the restore apps soon after changing the ROM and let you know

![Screenshot_2023-12-11-20-12-51-076_com.xayah.databackup.foss-edit.jpg](https://github.com/XayahSuSuSu/Android-DataBackup/assets/91434001/9a1cd159-7f5d-4b54-a05d-9890e73dc623)


 The new problem that exists is that telephony backup does not work and does not show any reaction

https://github.com/XayahSuSuSu/Android-DataBackup/assets/91434001/c8fda61a-61a7-472e-9c74-f88df3f6ea4e

**Comment by XayahSuSuSu** [comment]
> The new problem that exists is that telephony backup does not work and does not show any reaction

The telephony backup has not been implemented yet.
