### ISSUE TITLE
Options for saving without compression

### ISSUE THREAD

**Issue by elisenlebkuch** [XayahSuSuSu/Android-DataBackup#180]
A option to backup files without compressing them, for pictures, audio and other stuff where you don't want to lose any quality.

**Comment by XayahSuSuSu** [comment]
Have you checked the settings? There's an option named "Compression type", you can choose **tar** which means it will only package without compressing.

**Comment by elisenlebkuch** [comment]
Yes, I checked out settings, but I didn't know that tar is the equivalent to saving without compression. Thank you.
