### ISSUE TITLE
[Bug] 备份卡在剩余48

### ISSUE THREAD

**Issue by Goojoe** [XayahSuSuSu/Android-DataBackup#186]
小米平板5 安卓12
[log.zip](https://github.com/XayahSuSuSu/Android-DataBackup/files/13798275/log.zip)
本地备份和云端都这样，应该不用截图了 最后的备份应用是Zarchive pro

**Comment by XayahSuSuSu** [comment]
能提供本地备份卡住的日志吗

**Comment by Goojoe** [comment]
![Screenshot_20231231-190254_数据备份(1)](https://github.com/XayahSuSuSu/Android-DataBackup/assets/78355492/ded1a7ec-90da-4904-9128-370f84430f1c)

[log_1704020433603.zip](https://github.com/XayahSuSuSu/Android-DataBackup/files/13800902/log_1704020433603.zip)

**Comment by XayahSuSuSu** [comment]
请更新到[最新版本](https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/1.1.0-alpha06)
