### ISSUE TITLE
[Bug] sd卡格式识别错误

### ISSUE THREAD

**Issue by STTecCEO** [XayahSuSuSu/Android-DataBackup#189]
我的sd卡是exfat 在老版本中可以正常备份
新版会识别成？？texfat？？不支持的格式
![Screenshot_20240109-202331](https://github.com/XayahSuSuSu/Android-DataBackup/assets/35169436/b2cd0993-f1bd-4383-abf1-2a7c3ef4e031)

**Comment by XayahSuSuSu** [comment]
可以麻烦你用任意终端（MT的终端/Termux）输入以下内容截图吗？
```
su
mount | awk '$3 ~ /\mnt\/media_rw/ {print $3}'
```

**Comment by STTecCEO** [comment]
> 可以麻烦你用任意终端（MT的终端/Termux）输入以下内容截图吗？
> 
> ```
> su
> mount | awk '$3 ~ /\mnt\/media_rw/ {print $3}'
> ```

![Uploading Screenshot_20240109-215933.png…]()

**Comment by STTecCEO** [comment]
> 可以麻烦你用任意终端（MT的终端/Termux）输入以下内容截图吗？
> 
> ```
> su
> mount | awk '$3 ~ /\mnt\/media_rw/ {print $3}'
> ```

![Screenshot_20240109-215933](https://github.com/XayahSuSuSu/Android-DataBackup/assets/35169436/1fd3a3ac-6fd1-4aea-8c20-bc0804f49024)

**Comment by XayahSuSuSu** [comment]
```
mount | awk '$3 == "/mnt/media_rw/95A4-D1BD" {print $5}'
```
然后输入这些

**Comment by STTecCEO** [comment]
> ```
> mount | awk '$3 == "/mnt/media_rw/95A4-D1BD" {print $5}'
> ```
> 
> 然后输入这些

![Screenshot_20240109-221045](https://github.com/XayahSuSuSu/Android-DataBackup/assets/35169436/9f0518e4-8a67-40d6-ac87-6eceab58f37d)

**Comment by XayahSuSuSu** [comment]
> ![Screenshot_20240109-221045](https://private-user-images.githubusercontent.com/35169436/295231079-9f0518e4-8a67-40d6-ac87-6eceab58f37d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDk3OTMsIm5iZiI6MTcwNDgwOTQ5MywicGF0aCI6Ii8zNTE2OTQzNi8yOTUyMzEwNzktOWYwNTE4ZTQtOGE2Ny00MGQ2LWFjODctNmVjZWFiNThmMzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE0MTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxOTEwODYwZGE3MDlhMWExODg1NmNmOTgyYjE1NzA3YTlhZDg3NTNlYzBkOTY4NjU3N2QxYzI2YmYwMWFiM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zeZ4OA7NSPaNslhfmrNeDP4ArhRwfk602WTIcbwxDtM)

怪了，难道是解析出了问题
看看`mount | grep "/mnt/media_rw/95A4-D1BD"`呢

**Comment by STTecCEO** [comment]
> > ![Screenshot_20240109-221045](https://private-user-images.githubusercontent.com/35169436/295231079-9f0518e4-8a67-40d6-ac87-6eceab58f37d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDk3OTMsIm5iZiI6MTcwNDgwOTQ5MywicGF0aCI6Ii8zNTE2OTQzNi8yOTUyMzEwNzktOWYwNTE4ZTQtOGE2Ny00MGQ2LWFjODctNmVjZWFiNThmMzdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE0MTEzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxOTEwODYwZGE3MDlhMWExODg1NmNmOTgyYjE1NzA3YTlhZDg3NTNlYzBkOTY4NjU3N2QxYzI2YmYwMWFiM2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zeZ4OA7NSPaNslhfmrNeDP4ArhRwfk602WTIcbwxDtM)
> 
> 怪了，难道是解析出了问题 看看`mount | grep "/mnt/media_rw/95A4-D1BD"`呢

![Screenshot_20240109-223029](https://github.com/XayahSuSuSu/Android-DataBackup/assets/35169436/6eed3aa1-3220-436c-b785-0ec9f9586c17)

**Comment by XayahSuSuSu** [comment]
> ![Screenshot_20240109-223029](https://private-user-images.githubusercontent.com/35169436/295236699-6eed3aa1-3220-436c-b785-0ec9f9586c17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTA5ODYsIm5iZiI6MTcwNDgxMDY4NiwicGF0aCI6Ii8zNTE2OTQzNi8yOTUyMzY2OTktNmVlZDNhYTEtMzIyMC00MzZjLWI3ODUtMGVjOWY5NTg2YzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE0MzEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MzQ0ODVjMTdkOWI4MWYwNTMwMjBhZDkwNDUwM2YyY2Q1OTgzNTg1NmQ4NTM1NzdlYjBjY2JmMDAwYWU5YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ni4XvgNnSKOPf87aHMGuv7qQ2HwIlRGzgEBFySwMkOg)

Emm, 你的SD卡貌似确实是texfat格式，虽然我从来没见过这个格式

**Comment by STTecCEO** [comment]
> > ![Screenshot_20240109-223029](https://private-user-images.githubusercontent.com/35169436/295236699-6eed3aa1-3220-436c-b785-0ec9f9586c17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTA5ODYsIm5iZiI6MTcwNDgxMDY4NiwicGF0aCI6Ii8zNTE2OTQzNi8yOTUyMzY2OTktNmVlZDNhYTEtMzIyMC00MzZjLWI3ODUtMGVjOWY5NTg2YzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE0MzEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MzQ0ODVjMTdkOWI4MWYwNTMwMjBhZDkwNDUwM2YyY2Q1OTgzNTg1NmQ4NTM1NzdlYjBjY2JmMDAwYWU5YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ni4XvgNnSKOPf87aHMGuv7qQ2HwIlRGzgEBFySwMkOg)
> 
> Emm, 你的SD卡貌似确实是texfat格式，虽然我从来没见过这个格式

那能不能直接给这玩意放白名单 当exfat处理🤦‍♂️

**Comment by XayahSuSuSu** [comment]
> > > ![Screenshot_20240109-223029](https://private-user-images.githubusercontent.com/35169436/295236699-6eed3aa1-3220-436c-b785-0ec9f9586c17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MTA5ODYsIm5iZiI6MTcwNDgxMDY4NiwicGF0aCI6Ii8zNTE2OTQzNi8yOTUyMzY2OTktNmVlZDNhYTEtMzIyMC00MzZjLWI3ODUtMGVjOWY5NTg2YzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDE0MzEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MzQ0ODVjMTdkOWI4MWYwNTMwMjBhZDkwNDUwM2YyY2Q1OTgzNTg1NmQ4NTM1NzdlYjBjY2JmMDAwYWU5YjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ni4XvgNnSKOPf87aHMGuv7qQ2HwIlRGzgEBFySwMkOg)
> > 
> > 
> > Emm, 你的SD卡貌似确实是texfat格式，虽然我从来没见过这个格式
> 
> 那能不能直接给这玩意放白名单 当exfat处理🤦‍♂️

可以，刚查了下是exfat的[变体](https://en.wikipedia.org/wiki/Transaction-Safe_FAT_File_System)
