### ISSUE TITLE
希望备份界面加一个搜索APP的功能

### ISSUE THREAD

**Issue by k650dg4d2** [XayahSuSuSu/Android-DataBackup#19]
我有好几百应用，挨着找的话太麻烦了。希望可以直接搜索

**Comment by XayahSuSuSu** [comment]
> 我有好几百应用，挨着找的话太麻烦了。希望可以直接搜索

这个不是已经实现了吗
![Screenshot_2022-06-07-15-47-05-850_com xayah databackup](https://user-images.githubusercontent.com/44322170/172325524-53097887-354c-46f5-8133-54eb7484bed2.jpg)

另外建议阅读https://github.com/XayahSuSuSu/Android-DataBackup/issues/9
