### ISSUE TITLE
[Bug] 使用云端备份时无法备份和恢复媒体和通讯

### ISSUE THREAD

**Issue by zjw2017** [XayahSuSuSu/Android-DataBackup#192]
**Describe the bug**
Unable to backup and restore media and Telephone when using cloud backup

**To Reproduce**
1. Go to cloud button
2. Click on Backup
3. Click on Media
4. No feedback

**Expected behavior**
Correctly backup them

**Smartphone (please complete the following information):**
 - Device: Xiaomi 13 Ultra
 - OS: HyperOS 1.0 OS1.0.24.1.1.DEV
 - Version 1.1.0

**Comment by XayahSuSuSu** [comment]
还没做

**Comment by zjw2017** [comment]
好的，有计划就行。孩子以为会备份然后备份完就格式化了😭
