### ISSUE TITLE
[Feature] add support android 8

### ISSUE THREAD

**Issue by Mahantor** [XayahSuSuSu/Android-DataBackup#193]
**Describe the feature**

This app cannot be installed on Android 8
Please add Android 8 support to this great app
Thank you for your efforts

**Comment by XayahSuSuSu** [comment]
kk

**Comment by XayahSuSuSu** [comment]
https://github.com/XayahSuSuSu/Android-DataBackup/commit/0994ef8dbbe6b03bcd2f268bd6ead62d5c54e0e7
