### ISSUE TITLE
[Bug] 已备份的应用再次备份会将原有备份数据覆盖

### ISSUE THREAD

**Issue by 970844297** [XayahSuSuSu/Android-DataBackup#195]
出现此情况的应用是 白荆回廊
我备份了从QQ下载的该游戏后，卸载了该游戏，然后去虎牙再次下载该游戏，再次备份时，原来QQ版本的游戏备份就被覆盖了

 - Device: 小米12s
 - OS: Hyper OS 1.0.23.12.4.DEV
 - Version: 1.0.1-alpha06

**Comment by XayahSuSuSu** [comment]
1.0.x默认备份策略为覆盖，如果想要保留以前的备份，请在设置中切换为分时

**Comment by XayahSuSuSu** [comment]
另外建议更新到1.1.0
