### ISSUE TITLE
[Feature] Shizuku and Dhizuku Support

### ISSUE THREAD

**Issue by chengnan049** [XayahSuSuSu/Android-DataBackup#197]
**Describe the feature**
在未 Root 的设备上使用 [Shizuku](https://github.com/RikkaApps/Shizuku-API)，[Dhizuku](https://github.com/iamr0s/Dhizuku-API) 来恢复软件安装包

Use [Shizuku](https://github.com/RikkaApps/Shizuku-API) or [Dhizuku](https://github.com/iamr0s/Dhizuku-API) to restore application on non root device.

**Comment by XayahSuSuSu** [comment]
https://github.com/XayahSuSuSu/Android-DataBackup/issues/115
