### ISSUE TITLE
[Bug] 不支持匿名FTP、无密码FTP？

### ISSUE THREAD

**Issue by huangsijun17** [XayahSuSuSu/Android-DataBackup#201]
**Describe the bug**
云端备份时添加FTP链接必须输入密码，包括使用匿名用户anonymous。

**Comment by ywk94** [comment]
请教一下,哪个版本才支持云备份,我在https://apt.izzysoft.de/fdroid/index/apk/com.xayah.databackup下载的,但是没有找到云备份的任何按钮
