### ISSUE TITLE
建议添加 备份至电脑/从电脑恢复功能

### ISSUE THREAD

**Issue by sherkent** [XayahSuSuSu/Android-DataBackup#203]
添加 备份至电脑/从电脑恢复功能
用数据线等方法

**Comment by XayahSuSuSu** [comment]
Android目前并没有支持通过数据线直接对PC进行IO操作

**Comment by bryarrow** [comment]
是否可以考虑开发个电脑端拉起一个FTP服务器来实现该功能？

**Comment by XayahSuSuSu** [comment]
> 是否可以考虑开发个电脑端拉起一个FTP服务器来实现该功能？

没准可以用https://github.com/weixiansen574/HybridFileXfer
