### ISSUE TITLE
Search file/pkg name

### ISSUE THREAD

**Issue by painowest** [XayahSuSuSu/Android-DataBackup#208]
search file name or package name in local restore list not work (backup location: externalSD)

**Comment by XayahSuSuSu** [comment]
Which version are you using, and can you provide screenshots?

**Comment by painowest** [comment]
latest ver.
sorry, it's work but must select backup date first :D
can you make it auto search?

**Comment by XayahSuSuSu** [comment]
> can you make it auto search?

ofc :)
This will be optimized in the next version.

**Comment by painowest** [comment]
> > can you make it auto search?
> 
> ofc :) This will be optimized in the next version.

nice. terima kasih

**Comment by XayahSuSuSu** [comment]
Should be fixed in [alpha11](https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/9378315517)
