### ISSUE TITLE
[Bug] Micro Sd card format is wrongly detected.

### ISSUE THREAD

**Issue by sandeshkamboj** [XayahSuSuSu/Android-DataBackup#215]
**Describe the bug**
Whenever I try to select a directory in my micro SD card, it says microsd format is not supported and shows that it has Vfat format. However its format is EXT4 and I have confirmed it through my pc and custom recovery too.

**To Reproduce**
1.Open app.
2. Go to either backup or restore
2. Click on Directory under Utility section.
3. And there micro sd is shown unsupported.

**Expected behavior**
It should work with my microsd card as the format is supported.

**Screenshots**
![Screenshot_20240214-183940_DataBackup](https://github.com/XayahSuSuSu/Android-DataBackup/assets/109149418/ff4fd842-c120-480d-87f2-39e7189bb975)

**Smartphone (please complete the following information):**
 - Device: Realme Narzo 20 pro
 - OS: Lineage Os
 - Version: 14 Beta

**Comment by XayahSuSuSu** [comment]
Sry for late reply...
Can you type these commands in a certain terminal(e.g. [Termux](https://github.com/termux/termux-app)) and send me the screenshot?
```
su
mount | awk '$3 ~ /\mnt\/media_rw/'
```

**Comment by XayahSuSuSu** [comment]
With no response

**Comment by sandeshkamboj** [comment]
> With no response

I changed my device after that, so I couldn't test it and forgot to reply. Sorry for that.
