### ISSUE TITLE
[Feature] 数据备份增加备份user等数据而不备份data

### ISSUE THREAD

**Issue by Chen017** [XayahSuSuSu/Android-DataBackup#218]
国内软件例如阿里系 data是否恢复没有任何影响 只要备份user等其他数据就可保持登陆状态或是重新验证一次即可，所以data备份浪费空间时间，再比如大型游戏data可以直接联网下载 速度很快 而备份user可以保持登陆状态 不需要重新输入账号密码 因此只备份user等很高效

**Comment by XayahSuSuSu** [comment]
[alpha5](https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/7941171906)应该满足你的需求

**Comment by Chen017** [comment]
好的谢谢 之后能合入1.2.0吗

**Comment by Chen017** [comment]
alpha5版本好像没有全选的那个按钮 ？

**Comment by Chen017** [comment]
alpha5版本好像没有全选的那个按钮 ？

**Comment by XayahSuSuSu** [comment]
> alpha5版本好像没有全选的那个按钮 ？

alpha6有，请查看actions页面
