### ISSUE TITLE
[Feature] 希望在恢复的时候可以选择全部备份的应用，而不只是单单的时间显示

### ISSUE THREAD

**Issue by liuqianhe** [XayahSuSuSu/Android-DataBackup#219]
恢复的时候可以增加一个全局选择应用的功能就像旧版本一样，例如1.0.0sp1中的列表一样。

![img2](https://github.com/XayahSuSuSu/Android-DataBackup/assets/62452526/9a4e8434-5e31-47c7-bc2e-28b824344364)

而不只是只有一个按时间序列选择应用的选项

![img1](https://github.com/XayahSuSuSu/Android-DataBackup/assets/62452526/0ade8deb-ebed-4e43-ac77-2b1a6bf69eb8)

**Comment by liuqianhe** [comment]
好的，谢谢大佬😘

**Comment by XayahSuSuSu** [comment]
现在你可以在2.0.0中恢复全部应用了

**Comment by liuqianhe** [comment]
好的，感谢大佬
