### ISSUE TITLE
[Bug] Hidden files/dotFiles do not get backed up

### ISSUE THREAD

**Issue by ropapermaker** [XayahSuSuSu/Android-DataBackup#220]
**Describe the bug**
Backing up and restoring folders/files that have hidden/dotfiles does not work. 

**To Reproduce**
1. Create a folder that contains files or folders such as: `.ssh/`, `.nomedia`.
2. Backup and restore the folder.

**Expected behavior**
These files should be backed up.

**Screenshots**
Seems self-explanatory

**Smartphone (please complete the following information):**
 - Device: Oneplus 11
 - OS: Custom ROM - NamelessAOSP
 - Version Android 14

**Additional context**
Backed up from Android 13 and restored in Android 14 of the same custom ROM after a fresh install

**Comment by XayahSuSuSu** [comment]
This has been fixed in [alpha](https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/8129500215), can you give it a try?

**Comment by ropapermaker** [comment]
![Screenshot_20240303-200520_com mixplorer](https://github.com/XayahSuSuSu/Android-DataBackup/assets/58087674/b8ce55e2-c469-4c03-be06-734a4cf0a848)

Yes it works in the Alpha version, thank you :D.
