### ISSUE TITLE
[Bug] MIUI短信如何恢复？

### ISSUE THREAD

**Issue by IPjoshua** [XayahSuSuSu/Android-DataBackup#221]
Xiaomi 10  MIUI13

通讯按钮点击无效

应用中备份com.android.providers.telephony和com.android.mms数据后，恢复短音无效

手动覆盖com.android.mms\databases\bugle文件后，短信记录依旧无法恢复

求问MIUI短信如何恢复呢？

**Comment by XayahSuSuSu** [comment]
直接备份应用无法恢复，需要使用ContentProvider读取数据库中有效字段值，最后重建才能正常读取，目前app仅1.0.1-alpha版本支持短信备份恢复

**Comment by IPjoshua** [comment]
> ContentProvider

有安装1.0.1-alph3，只能读取com.android.providers.telephony下的短信记录，com.android.mms的短信记录无法识别呢╮(╯_╰)╭

**Comment by XayahSuSuSu** [comment]
> com.android.mms的短信记录无法识别呢╮(╯_╰)╭

com.android.mms下的数据库文件貌似不包含真正的短信内容吧，我这边只在其中找到了一些黄页和关联数据

**Comment by IPjoshua** [comment]
> > com.android.mms的短信无法记录识别呢╮(╯_╰)╭
> 
> com.android.mms下的数据库文件显然不包含真正的短信内容吧，我只是在其中找到了一些黄页和关联数据

com.android.mms\databases\bugle这个数据库文件里面有短信记录呢

**Comment by XayahSuSuSu** [comment]
> com.android.mms\databases\bugle

目前看下来这个数据库只是短信应用本地用于展示的缓存？
至少我在此数据库中能看到的短信内容都能在`mmssms.db`中找到原始数据

**Comment by XayahSuSuSu** [comment]
> 有安装1.0.1-alph3，只能读取com.android.providers.telephony下的短信记录，com.android.mms的短信记录无法识别呢╮(╯_╰)╭

你是如何判断的呢

**Comment by IPjoshua** [comment]
> > com.android.mms\databases\bugle
> 
> 目前看下来这个数据库只是短信应用本地用于展示的缓存？ 至少我在此数据库中能看到的短信内容都能在`mmssms.db`中找到原始数据

明白了，感谢指点，辛苦了！

**Comment by IPjoshua** [comment]
> > 已安装1.0.1-alph3，只能读取com.android.providers.telephony下的短信记录，com.android.mms的短信记录无法识别呢╮(╯_╰)╭
> 
> 你是如何判断的呢
大概是个乌龙 可能是小米同步的问题吧 
最初小米同步到本地 用1.0.1备份发现短信不完整，就找原因
看到com.android.mms\databases\bugle里面有最新记录，mmssms.db记得当时只有部分记录（就是备份那部份）
昨晚看mmssms.db里面记录又完整了，用1.0.1又能备份全部记录了
