### ISSUE TITLE
[Bug] 恢复列表丢失,SMB传输选择文件应用未响应,SMB未校验用户密码及目录情况。

### ISSUE THREAD

**Issue by limitcool** [XayahSuSuSu/Android-DataBackup#228]
之前用旧系统备份之后进行测试是可以获取到全部的恢复列表的，但是系统重装之后发现恢复列表里面只有两个应用,查看了目录结构,发现是有一个`package_restore_config.pb`的文件来记录恢复列表,里面竟然只有两个应用, 我尝试删除了该文件,发现不会重新索引列表,另外云端的SMB传输有很多bug,填写账号密码和目录之后并不会校验是否可以连接到SMB服务器,会导致在选择远程目录列表卡死导致未响应,并且此时如果填写正确的目录也无法连接上,必须清除数据重新填写远程信息才可以。程序应该是有缓存没有清除,默认使用了旧的错误的配置,正确的配置无法更新上。
版本:1.1.0
现在我需要知道如何通过应用生成新的恢复列表`package_restore_config.pb`,可以帮助我吗？

**Comment by XayahSuSuSu** [comment]
1.1.0不支持重建云端恢复列表，临时解决办法是下载到本地重载恢复

**Comment by XayahSuSuSu** [comment]
Should be fixed in [alpha11](https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/9378315517)
