### ISSUE TITLE
[Feature]  第一次加载应用列表太慢了，之后更新应用列表也影响体验，是否功能上应该有所取舍

### ISSUE THREAD

**Issue by seeyou-github** [XayahSuSuSu/Android-DataBackup#229]
如题，估计加载应用时，读取所有应用数据大小，造成长时间等待。

是否有必要加载所有应用数据大小？

是否可以考虑，在用户选择了要备份的应用后，仅仅显示已经选择的应用数据大小？

没有选择的应用，意味着不关心其数据大小？

**Comment by XayahSuSuSu** [comment]
哪个版本？将来更新的版本将不再自动刷新列表，改为用户手动下拉刷新

**Comment by XayahSuSuSu** [comment]
> > 哪个版本？将来更新的版本将不再自动刷新列表，改为用户手动下拉刷新
> 
> 最新版本

1.1.0？试试actions里最新的
