### ISSUE TITLE
[Bug] just error

### ISSUE THREAD

**Issue by Fan-Bob** [XayahSuSuSu/Android-DataBackup#232]
![Screenshot_20240423-005111](https://github.com/XayahSuSuSu/Android-DataBackup/assets/139612414/74d45f3a-ed2b-4c3c-8ca9-8edab7ce4593)
always error，Details are in the picture

**Comment by XayahSuSuSu** [comment]
Should be fixed in [alpha11](https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/9378315517)
