### ISSUE TITLE
[Bug] 无法识别基于 APatch的Root方案

### ISSUE THREAD

**Issue by github-faning-net** [XayahSuSuSu/Android-DataBackup#234]
**Screenshots**

![Screenshot_20240516-164856_APatch](https://github.com/XayahSuSuSu/Android-DataBackup/assets/161269929/1026cbee-8b26-47ce-983c-3924c4d763a3)
![Screenshot_20240516-164621_APatch](https://github.com/XayahSuSuSu/Android-DataBackup/assets/161269929/a74e2969-a499-4683-b244-77c5c3b65608)
![Screenshot_20240516-164728_数据备份](https://github.com/XayahSuSuSu/Android-DataBackup/assets/161269929/9e5bc922-d929-453e-aa34-6ae8a6b789ac)
![Screenshot_20240516-164718_数据备份](https://github.com/XayahSuSuSu/Android-DataBackup/assets/161269929/27cefc58-0bb5-4525-993e-5d06765817c4)

**Smartphone (please complete the following information):**
 - Device: [XiaoMi6]
 - OS: [e.g. MIUI14, Android13]
 - Version [LineageOS-21]

**Additional context**
No.

**Comment by XayahSuSuSu** [comment]
https://github.com/bmax121/APatch/issues/439
Databackup依赖于su建立Rootservice，这个问题最好由Apatch上游修复，例如KernelSU提供的[workaroud](https://github.com/tiann/KernelSU/tree/main/userspace/su)

**Comment by XayahSuSuSu** [comment]
不过看你截图里的su程序被命名为kp，能否麻烦你那边帮忙测试下termux调用`kp`能否进入rootshell环境，如果可以这边倒是可以增加一个自定义su程序的功能来修复这个问题

**Comment by XayahSuSuSu** [comment]
@github-faning-net 请尝试将自定义su文件设置为`kp`，重启应用后再测试能否通过检测
[DataBackup-9-arm64-v8a-alpha-release.zip](https://github.com/XayahSuSuSu/Android-DataBackup/files/15479907/DataBackup-9-arm64-v8a-alpha-release.zip)

**Comment by github-faning-net** [comment]
> @github-faning-net 请尝试将自定义su文件设置为`kp`，重启应用后再测试能否通过检测 [DataBackup-9-arm64-v8a-alpha-release.zip](https://github.com/XayahSuSuSu/Android-DataBackup/files/15479907/DataBackup-9-arm64-v8a-alpha-release.zip)

首先感谢您的回复。

`su` 文件设置为 `kp` 可以通过检测，但是本地应用备份失败；另外，针对 `android14`，短信和联系人的快捷操作无法开启。

![Screenshot_20240531-105432_APatch](https://github.com/XayahSuSuSu/Android-DataBackup/assets/161269929/b46505d0-87ac-4d88-a486-1ef86f53cf74)

![Screenshot_20240531-105702_DataBackup alpha](https://github.com/XayahSuSuSu/Android-DataBackup/assets/161269929/6afd7664-9e00-4706-8f3e-ac01b29e9480)

![Screenshot_20240531-105155_DataBackup alpha](https://github.com/XayahSuSuSu/Android-DataBackup/assets/161269929/9719a375-cb5b-470c-9fcc-685d7c11385e)

**Comment by XayahSuSuSu** [comment]
短信联系人以及文件备份还没有做完，所以目前是禁用状态

能否麻烦再测试下这个版本，另外备份完后能否把`/data/data/com.xayah.databackup.alpha/files/log`打包上传一下
[DataBackup-9-arm64-v8a-alpha-release.zip](https://github.com/user-attachments/files/15508070/DataBackup-9-arm64-v8a-alpha-release.zip)

**Comment by github-faning-net** [comment]
> 短信联系人以及文件备份还没有做完，所以目前是禁用状态
> 
> 能否麻烦再测试下这个版本，另外备份完后能否把`/data/data/com.xayah.databackup.alpha/files/log`打包上传一下 [DataBackup-9-arm64-v8a-alpha-release.zip](https://github.com/user-attachments/files/15508070/DataBackup-9-arm64-v8a-alpha-release.zip)

用这个版本可以正常备份。神奇的事情是，再用上一个版本[DataBackup-9-arm64-v8a-alpha-release.zip](https://github.com/XayahSuSuSu/Android-DataBackup/files/15479907/DataBackup-9-arm64-v8a-alpha-release.zip)也可以正常备份了。

**Comment by XayahSuSuSu** [comment]
> > 短信联系人以及文件备份还没有做完，所以目前是禁用状态
> > 能否麻烦再测试下这个版本，另外备份完后能否把`/data/data/com.xayah.databackup.alpha/files/log`打包上传一下 [DataBackup-9-arm64-v8a-alpha-release.zip](https://github.com/user-attachments/files/15508070/DataBackup-9-arm64-v8a-alpha-release.zip)
> 
> 用这个版本可以正常备份。神奇的事情是，再用上一个版本[DataBackup-9-arm64-v8a-alpha-release.zip](https://github.com/XayahSuSuSu/Android-DataBackup/files/15479907/DataBackup-9-arm64-v8a-alpha-release.zip)也可以正常备份了。

感谢
