### ISSUE TITLE
[Bug] webdav can not handle 302 redirects

### ISSUE THREAD

**Issue by WXZhao7** [XayahSuSuSu/Android-DataBackup#239]
**Describe the bug**
使用带有302重定向的网盘Webdav时无法读取路径，`设置远程`时选择目录只显示根目录，点击进入则为空白

在linux上部分软件也有遇到这个问题了，所幸davfs2支持，倒也可以通过挂载本地解决，安卓上就没有办法了。

**Screenshots**
![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/56864878/04f9819c-ae48-4cb2-9e64-1dff9bf33c61)

**Smartphone (please complete the following information):**
 - Device: RedMi note 12 turbo
 - OS: MIUI14, Android13
 - Version: 1.1.0
![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/56864878/bfd54fe0-6bd9-4e70-abfc-db94ad078f82)

**Additional context**

**Comment by XayahSuSuSu** [comment]
试试https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/9378315517

**Comment by WXZhao7** [comment]
工作正常了，不论是选择挂载点，还是上传都没问题，重载恢复也是正常运行。期待正式更新
![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/56864878/5d47c424-d1dd-4719-af7e-935b67f50de3)
