### ISSUE TITLE
[Bug] I need to regenerate package_restore_config.pb

### ISSUE THREAD

**Issue by ha2ked** [XayahSuSuSu/Android-DataBackup#242]
My package_restore_config.pb file got corrupted and I can't generate a new one. So if there is any way that I could regenerate the file without using the phone that I made the restore please tell me.

de4uth

**Comment by XayahSuSuSu** [comment]
Please try to use the latest [CI build](https://github.com/XayahSuSuSu/Android-DataBackup/actions/workflows/build.yaml) to reload and restore apps
