### ISSUE TITLE
[Bug] 备份目录存在多个重复无法删除

### ISSUE THREAD

**Issue by 20171213** [XayahSuSuSu/Android-DataBackup#246]
![Screenshot_2024-07-01-10-32-46-291_com.xayah.databackup.premium.jpg](https://github.com/XayahSuSuSu/Android-DataBackup/assets/34502902/941d6ede-1ae9-443c-ac5e-bd90a88734d4)

如图，升级到2.0版本后发现的，全都是同样的路径

型号小米14，版本hyperos 1.0.42.0 安卓14

**Comment by XayahSuSuSu** [comment]
从什么版本升级过来的，试试清除应用数据呢

**Comment by 20171213** [comment]
> 从什么版本升级过来的，试试清除应用数据呢

从1.1.0升级，清除数据也没有用，在向导界面也能看到这个问题

![Screenrecorder-2024-07-03-01-05-14-22_小萌GIF_20240703_010621.gif](https://github.com/XayahSuSuSu/Android-DataBackup/assets/34502902/24859f7f-310d-47a2-a899-c03e4216220d)

**Comment by XayahSuSuSu** [comment]
https://github.com/XayahSuSuSu/Android-DataBackup/commit/cdf9d3f268443acf6d37c90c693f4177705595c4
