### ISSUE TITLE
[Bug] 根据ABI编译失效了

### ISSUE THREAD

**Issue by Doddddd** [XayahSuSuSu/Android-DataBackup#247]

**Comment by XayahSuSuSu** [comment]
APK? BIN？

**Comment by Doddddd** [comment]
> APK? BIN？

apk

**Comment by XayahSuSuSu** [comment]
报什么错？
删掉
https://github.com/XayahSuSuSu/Android-DataBackup/blob/7dc02df804323acaf715a21f9a21cd8d35910a12/source/build-logic/convention/src/main/kotlin/ApplicationCommonConventionPlugin.kt#L14-L21

https://github.com/XayahSuSuSu/Android-DataBackup/blob/7dc02df804323acaf715a21f9a21cd8d35910a12/source/build-logic/convention/src/main/kotlin/ApplicationCommonConventionPlugin.kt#L29

试试

**Comment by Doddddd** [comment]
> 报什么错？ 删掉
> 
> https://github.com/XayahSuSuSu/Android-DataBackup/blob/7dc02df804323acaf715a21f9a21cd8d35910a12/source/build-logic/convention/src/main/kotlin/ApplicationCommonConventionPlugin.kt#L14-L21
> 
> https://github.com/XayahSuSuSu/Android-DataBackup/blob/7dc02df804323acaf715a21f9a21cd8d35910a12/source/build-logic/convention/src/main/kotlin/ApplicationCommonConventionPlugin.kt#L29
> 
> 试试

![image](https://github.com/XayahSuSuSu/Android-DataBackup/assets/88972478/dbf381ae-9ffa-46c7-b578-adef61950daa)
这里的库不能拆分吗？

**Comment by XayahSuSuSu** [comment]
https://github.com/LottieFiles/dotlottie-android/issues/24
