### ISSUE TITLE
[Bug] 未勾选的备份内容导致备份失败提示

### ISSUE THREAD

**Issue by lie-jiu** [XayahSuSuSu/Android-DataBackup#251]
手动取消的备份内容应该打勾
不然每次备份完后全是提示失败😂

**Comment by CuteXayah** [comment]
云端？

**Comment by lie-jiu** [comment]
> 云端？

是的
本地不会吗

**Comment by XayahSuSuSu** [comment]
已在[2.0.1](https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/2.0.1)中修复
