### ISSUE TITLE
[Feature] add android 7.0 support please

### ISSUE THREAD

**Issue by SiriusNeo1** [XayahSuSuSu/Android-DataBackup#254]
**Describe the feature**

This wonderful app cannot be installed on Android 7.0 (API 24)
Please add Android 7.0 support to this great app
Thank you for your efforts!

**Comment by SiriusNeo1** [comment]
Thanks a lot once more!
I am excited to use this beautiful and excellent app on my old phone in the next release! :D

**Comment by XayahSuSuSu** [comment]
Can you have a try on it?
https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/9928481406

**Comment by SiriusNeo1** [comment]
> Can you have a try on it? https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/9928481406

get stuck on the splash screen
![Screenshot_2024-07-14-22-36-01-621_com xayah databackup alpha](https://github.com/user-attachments/assets/6bdd673d-48e9-4ace-a0d2-e1b13bf13b7e)

**Comment by XayahSuSuSu** [comment]
> get stuck on the splash screen Device:Redmi Note 4X System:Miui 11 9.10.10 beta,Android 7.0 ![Screenshot_2024-07-14-22-36-01-621_com xayah databackup alpha](https://private-user-images.githubusercontent.com/165260083/348550594-6bdd673d-48e9-4ace-a0d2-e1b13bf13b7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5Njg5OTMsIm5iZiI6MTcyMDk2ODY5MywicGF0aCI6Ii8xNjUyNjAwODMvMzQ4NTUwNTk0LTZiZGQ2NzNkLTQ4ZTktNGFjZS1hMGQyLWUxYjEzYmYxM2I3ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQxNDUxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzE2ZTEyMjI4MGZkNzE4MmIyZGEzYmNkNjNhYmQzMDRmZGRkYWNiOTc5M2Q0ODhjNzhkNTcyN2ZhYzMzZjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TDxf3tos6G2UsXPCP0mnqgA3wOmi5dXWQ-pYguGmVvQ)

Does reboot or reinstallation work?

**Comment by SiriusNeo1** [comment]
> > get stuck on the splash screen Device:Redmi Note 4X System:Miui 11 9.10.10 beta,Android 7.0 ![Screenshot_2024-07-14-22-36-01-621_com xayah databackup alpha](https://private-user-images.githubusercontent.com/165260083/348550594-6bdd673d-48e9-4ace-a0d2-e1b13bf13b7e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5Njg5OTMsIm5iZiI6MTcyMDk2ODY5MywicGF0aCI6Ii8xNjUyNjAwODMvMzQ4NTUwNTk0LTZiZGQ2NzNkLTQ4ZTktNGFjZS1hMGQyLWUxYjEzYmYxM2I3ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNFQxNDUxMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzE2ZTEyMjI4MGZkNzE4MmIyZGEzYmNkNjNhYmQzMDRmZGRkYWNiOTc5M2Q0ODhjNzhkNTcyN2ZhYzMzZjBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TDxf3tos6G2UsXPCP0mnqgA3wOmi5dXWQ-pYguGmVvQ)
> 
> Does reboot or reinstallation work?

it doesnt work,log is there:
07-14 22:59:36.045  8974  8974 E AndroidRuntime: FATAL EXCEPTION: main
07-14 22:59:36.045  8974  8974 E AndroidRuntime: Process: com.xayah.databackup.alpha, PID: 8974
07-14 22:59:36.045  8974  8974 E AndroidRuntime: java.lang.IllegalStateException: CompositionLocal LocalLifecycleOwner not present
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at o4.c$a.invoke(SourceFile:9)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at eb.m.getValue(SourceFile:1)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.z.a(SourceFile:31)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.k.u(SourceFile:1)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at o4.b.c(SourceFile:9)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at com.xayah.feature.crash.MainActivity$onCreate$1$1.invoke(SourceFile:2)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at com.xayah.feature.crash.MainActivity$onCreate$1$1.invoke(SourceFile:1)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x0.a.invoke(SourceFile:4)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.x.a(SourceFile:19)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at com.xayah.core.ui.theme.ThemeKt$DataBackupTheme$3.invoke(SourceFile:2)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at com.xayah.core.ui.theme.ThemeKt$DataBackupTheme$3.invoke(SourceFile:1)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x0.a.invoke(SourceFile:4)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.x.a(SourceFile:19)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at n0.o8.a(SourceFile:75)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at n0.a3$a.invoke(SourceFile:32)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x0.a.invoke(SourceFile:4)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.x.b(SourceFile:19)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at n0.a3.a(SourceFile:312)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at com.xayah.core.ui.theme.ThemeKt.DataBackupTheme(SourceFile:273)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at com.xayah.feature.crash.MainActivity$onCreate$1.invoke(SourceFile:2)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at com.xayah.feature.crash.MainActivity$onCreate$1.invoke(SourceFile:1)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x0.a.invoke(SourceFile:4)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.a1.Content(SourceFile:24)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.a$a.invoke(SourceFile:29)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x0.a.invoke(SourceFile:4)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.x.b(SourceFile:19)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.b1.a(SourceFile:280)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.h0$i.invoke(SourceFile:33)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x0.a.invoke(SourceFile:4)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.x.b(SourceFile:19)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.h0.a(SourceFile:482)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.n3.invoke(SourceFile:33)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x0.a.invoke(SourceFile:4)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.x.a(SourceFile:19)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.o3.invoke(SourceFile:141)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x0.a.invoke(SourceFile:4)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at b4.a.I0(SourceFile:1)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.k.R(SourceFile:118)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.k.M(SourceFile:11)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.u.k(SourceFile:34)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.f2.a(SourceFile:41)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at p0.u.o(SourceFile:11)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.p3$a.invoke(SourceFile:57)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.p.setOnViewTreeOwnersAvailable(SourceFile:1)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.p3.o(SourceFile:1)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.p3.onStateChanged(SourceFile:1)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at androidx.lifecycle.t$a.a(SourceFile:23)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at androidx.lifecycle.t.a(SourceFile:229)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.p3$a.invoke(SourceFile:25)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at x1.p.onAttachedToWindow(SourceFile:104)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.View.dispatchAttachedToWindow(View.java:15420)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2955)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2962)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1560)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1290)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6399)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:873)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:685)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:621)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:859)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:754)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:165)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6378)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
07-14 22:59:36.045  8974  8974 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
07-14 22:59:36.052  8974  8974 I Timeline: Timeline: Activity_launch_request time:147699 intent:Intent { flg=0x10000000 cmp=com.xayah.databackup.alpha/com.xayah.feature.crash.MainActivity (has extras) }
07-14 22:59:36.053  1487  3087 I ActivityManager: START u0 {flg=0x10000000 cmp=com.xayah.databackup.alpha/com.xayah.feature.crash.MainActivity (has extras)} from uid 10202 on display 0
07-14 22:59:36.058  1487  3087 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
07-14 22:59:36.063  8974  8974 I art     : System.exit called, status: 0
07-14 22:59:36.063  8974  8974 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
07-14 22:59:36.083  1487  4779 D GraphicsStats: Buffer count: 4
07-14 22:59:36.083  1487  7093 I WindowManager: WIN DEATH: Window{eb3975d u0 com.xayah.databackup.alpha/com.xayah.feature.crash.MainActivity}
07-14 22:59:36.083  1487  2952 I ActivityManager: Process com.xayah.databackup.alpha (pid 8974) has died: fore T 
07-14 22:59:36.084  1487  2952 W ActivityManager: Force removing ActivityRecord{acdf8a5 u0 com.xayah.databackup.alpha/com.xayah.feature.crash.MainActivity t452}: app died, no saved state
07-14 22:59:36.097  1487  2952 I ActivityManager: Start proc 9005:com.xayah.databackup.alpha/u0a202 for activity com.xayah.databackup.alpha/com.xayah.feature.crash.MainActivity caller=com.xayah.databackup.alpha

**Comment by XayahSuSuSu** [comment]
Thanks for logs, this should be fixed: https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/9941031015

**Comment by SiriusNeo1** [comment]
It's fixed. Thanks!
