### ISSUE TITLE
where can I find the source of libsardine?

### ISSUE THREAD

**Issue by IzzySoft** [XayahSuSuSu/Android-DataBackup#259]
I find the reference

    import com.xayah.libsardine.impl.OkHttpSardine

but cannot find the library itself anywhere. Could you please point me to its source code? Thanks in advance!

**Comment by IzzySoft** [comment]
PS: similarly, also `com.dotlottie.dlplayer` and `com.lottiefiles.dotlottie`…

**Comment by XayahSuSuSu** [comment]
https://github.com/XayahSuSuSu/sardine-next
https://github.com/LottieFiles/dotlottie-android

**Comment by IzzySoft** [comment]
Thanks! Any clue what license DotLottie is using? I cannot find it mentioned. No license would mean "all rights reserved", and thus "not libre/FOSS"…

**Comment by IzzySoft** [comment]
(raised the question [here](https://github.com/LottieFiles/dotlottie-android/issues/29))

**Comment by XayahSuSuSu** [comment]
> Thanks! Any clue what license DotLottie is using? I cannot find it mentioned. No license would mean "all rights reserved", and thus "not libre/FOSS"…

Actually I didnt notice this issue, maybe we should wait for their reply

**Comment by IzzySoft** [comment]
Guess we have no other choice then, yeah. Hopefully they just forgot the license file or are at least open to add a license, else the lib would count as non-free… (clicking the link) Ah, my wish was granted – it's MIT \o/

All solved then, so I close the issue. Thanks a lot once more!
