### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by toonvank** [XayahSuSuSu/Android-DataBackup#262]
Following exception when trying to connect to WebDav: 'java.lang.RuntimeException: java.security.KeyStoreException: BKS not found"

Try to connect to webdav

Expected to test connection

![Screenshot_20240710-095949.png](https://github.com/XayahSuSuSu/Android-DataBackup/assets/61182641/6c98f88b-611e-44d3-8dc2-9c2ac8d1f988
)

 - Device: Motorola G54
 - OS: Android 14
 - Version 2.0.1

**Comment by XayahSuSuSu** [comment]
This has been fixed in https://github.com/XayahSuSuSu/Android-DataBackup/commit/aa9312fb8884a6873278a3043abbf2dc06aeeab1, please wait for next build
