### ISSUE TITLE
[Bug] X25519 KeyPairGenerator not available

### ISSUE THREAD

**Issue by katyo** [XayahSuSuSu/Android-DataBackup#264]
**Describe the bug**
When I try to add SFTP server I see the following message: "X25519 KeyPairGenerator not available".

**To Reproduce**
1. Go to 'Cloud' -> 'Add account'
2. Click on 'SFTP'
4. Fill server address, username and password
5. Click on 'Path' or 'Check connection'
6. See an error message

**Expected behavior**
Ability to set path to store backups

**Smartphone**
 - Device: Xiaomi Redmi 4X
 - OS: Android 10 [Havoc OS]
 - Version: 2.0.1

**Comment by XayahSuSuSu** [comment]
Can you provide a detailed log?
It's in `/data/data/com.xayah.databackup.xxx/files/log`

**Comment by XayahSuSuSu** [comment]
Please have a try on it
[DataBackup-2.0.1-arm64-v8a-foss-release.zip](https://github.com/user-attachments/files/16171258/DataBackup-2.0.1-arm64-v8a-foss-release.zip)

**Comment by katyo** [comment]
> Please have a try on it [DataBackup-2.0.1-arm64-v8a-foss-release.zip](https://github.com/user-attachments/files/16171258/DataBackup-2.0.1-arm64-v8a-foss-release.zip)

@XayahSuSuSu This release works as expected for me. Also I successfully tested webdav via https. Thank you so much!
