### ISSUE TITLE
[Bug] F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [XayahSuSuSu/Android-DataBackup#267]
**Describe the bug**
Apparently it's caused by https://github.com/XayahSuSuSu/Android-DataBackup/pull/260. The language list needs to be sorted.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi 10 Ultra]
 - OS: [e.g. MIUI14, Android13]
 - Version [e.g. Beta-4.3.7]

**Additional context**

**Comment by XayahSuSuSu** [comment]
Should be fixed in https://github.com/XayahSuSuSu/Android-DataBackup/commit/cccd485c58c157ffb850e12e2a6e14a78198888d
How can we test it?

**Comment by linsui** [comment]
You can upload the armv8 apk here.

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/7325244591/artifacts/browse/tmp/

**Comment by XayahSuSuSu** [comment]
[DataBackup-2.0.2-arm64-v8a-foss-release.zip](https://github.com/user-attachments/files/16190996/DataBackup-2.0.2-arm64-v8a-foss-release.zip)

**Comment by linsui** [comment]
It's fixed. Thanks!
