### ISSUE TITLE
[Feature] 基于修改时间等判断备份是否应该更新

### ISSUE THREAD

**Issue by poly000** [XayahSuSuSu/Android-DataBackup#28]
相较于 #26 ，还可以很大减少备份时间
如果生成一个此次增加/修改文件列表 还可以方便用户增量更新自己的备份（对于USB 2.0用户备份速度加快应该会很明显……）

**Comment by XayahSuSuSu** [comment]
目前已实现原脚本基于大小的比较方法，还未推送更新
https://github.com/XayahSuSuSu/Android-DataBackup/commit/62ef199f43f13b93d8fc4e8bf7cb23b1cd6daa20
https://github.com/XayahSuSuSu/Android-DataBackup/commit/53787405bd88206242c0ed952146416c02530a86
https://github.com/XayahSuSuSu/Android-DataBackup/commit/2c11214ecb2dbbeed72b057b712ba2c8c05a8058

**Comment by XayahSuSuSu** [comment]
> 

有没有示例可以测试，据脚本原作者说从未遇到过这种问题

**Comment by XayahSuSuSu** [comment]
另外我认为这个功能实现之后 https://github.com/XayahSuSuSu/Android-DataBackup/issues/26 似乎没有必要了，你觉得呢

**Comment by XayahSuSuSu** [comment]
已实现基于大小的备份更新判断，此Issue暂时关闭
