### ISSUE TITLE
[github action tutorial]github action使用求教

### ISSUE THREAD

**Issue by FiberStudio** [XayahSuSuSu/Android-DataBackup#281]
求教github action中STORE_FILE和ENCODED_STRING两个变量应该设置为什么值。
之前遇到个小bug想贡献份力量，结果fork之后使用action build发现缺少两个环境变量。
求解，谢谢。

**Comment by XayahSuSuSu** [comment]
https://medium.com/@dcostalloyd90/automating-android-builds-with-github-actions-a-step-by-step-guide-2a02a54f59cd
参考下

**Comment by FiberStudio** [comment]
> https://medium.com/@dcostalloyd90/automating-android-builds-with-github-actions-a-step-by-step-guide-2a02a54f59cd 参考下

收到，感谢感谢
