### ISSUE TITLE
[Feature] 可否增加使用shell命令来激活备份？

### ISSUE THREAD

**Issue by soulpursuit** [XayahSuSuSu/Android-DataBackup#287]
**Describe the feature**
A clear and concise description.
希望可以使用命令行或者能提供让其他APP调用的接口，这样用tacker或者macrodroid类的自动化软件，定期对APP进行备份

**Comment by XayahSuSuSu** [comment]
https://github.com/YAWAsau/backup_script
建议使用脚本自动化
