### ISSUE TITLE
[Bug] App crash caused by large sized icon

### ISSUE THREAD

**Issue by Explorare** [XayahSuSuSu/Android-DataBackup#302]
**Describe the bug**
The application would crash while rendering / restoring the specific app, for example in app list or app restore view.

**To Reproduce**
1. Place the [backup file](https://file.io/8b74gcJIirm6) under `\DataBackup\apps`
2. Open restore view and the app will crash if the icon is rendered in that view. If not, open the restore app view and scroll down to trigger the rendering, which will lead to immediately crash. 

**Expected behavior**

**Screenshots**
![Screenshot_20240904-143120_DataBackup](https://github.com/user-attachments/assets/363e67d4-4874-43f2-bb3d-432446084496)

**Smartphone (please complete the following information):**
 - Device: Oneplus 7 Pro
 - OS: LineageOS 21
 - App version: 2.0.3-FOSS

**Comment by XayahSuSuSu** [comment]
Weird icon size, can you clear the data and cache then try it again?
I didn't reproduce this issue using your zip file
![image](https://github.com/user-attachments/assets/e7c84c22-e7d2-4368-a65f-f1e59983f0d9)

**Comment by Explorare** [comment]
The app will crash if that icon showed in the preview. Remove it from backup folder and clear data and cache will fix the issue. Add the backup will introduce the crash issue again. I've tried 100+ apps and only this one causing the issue. Maybe it's a system specific issue. The backup is made in H2OS 10 and restored in LOS 21. So maybe the icon format is incompatible.

**Comment by XayahSuSuSu** [comment]
Can you send the `icon.tar` in `DataBackup/configs` dir?

**Comment by Explorare** [comment]
The size of the icon causing the issue is 1.2MB, double the size of others. 
[icon.tar](https://file.io/uq66iamfvOtd)

**Comment by XayahSuSuSu** [comment]
Will fix in next build

**Comment by XayahSuSuSu** [comment]
Should be fixed in https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/10757628047
