### ISSUE TITLE
[Feature]批量选择是否备份应用数据或者安装包

### ISSUE THREAD

**Issue by Aloazny** [XayahSuSuSu/Android-DataBackup#304]
> ## 标题：[Feature]批量选择是否备份应用数据或者安装包 

- 内容: 大佬， 可不可以批量选择是否备份应用数据或者安装包，类似Migrate-NG (new)那样。
- 如图: ![Screenshot_2024-09-11-09-42-03-351_balti.migrate.ng.jpg](https://github.com/user-attachments/assets/1703c88c-331a-4ffd-9a4b-7f00167fe838)

**Comment by XayahSuSuSu** [comment]
2.0.3点击标题栏右边第二个按钮，可以为已选择的应用批量修改需要备份的数据项

**Comment by Aloazny** [comment]
好的，感谢大佬，翻了半天都没找到，还以为没有，对不起，打扰了。
