### ISSUE TITLE
[Bug] Tick Icon is blocking the last application's Data option 

### ISSUE THREAD

**Issue by Raul1198** [XayahSuSuSu/Android-DataBackup#31]
![Screenshot_20220625-104919_DataBackup~01](https://user-images.githubusercontent.com/29801315/175759731-8496bed8-3233-492b-9262-9847fe941534.png)
Here in the above image when scrolling down the to the last option in Backup the tick is blocking YouTube's Data Option, only the Application is available

**Comment by XayahSuSuSu** [comment]
Will try to optimize that, thx for feedback

**Comment by XayahSuSuSu** [comment]
It's been optimized since Beta-4.0.0
