### ISSUE TITLE
[Feature] Alpha19功能

### ISSUE THREAD

**Issue by Goojoe** [XayahSuSuSu/Android-DataBackup#315]
1.选择数据大小排序，没有显示总数据大小
2.configurations.json能备份并随着文件云端备份传输到目标configs文件夹吗（目前这个文件夹只有icon.tar），毕竟最后配置文件和apk都是要用usb传输到手机的
3.选择文件添加后就不能删除了，没有被选择的文件夹列表会随着configurations.json导出

**Comment by XayahSuSuSu** [comment]
1. 目前的设计是这样，如果显示额外的信息，一页显示的内容就会少很多
2. 2.0.4支持了此功能
3. 文件可以在文件详情里删除
