### ISSUE TITLE
[Bug] 使用充电控制模块会被识别为otg

### ISSUE THREAD

**Issue by vtrayy** [XayahSuSuSu/Android-DataBackup#32]
脚本版也有这个问题
![Screenshot_2022-06-25-20-22-12-687_io github vvb2060 magisk](https://user-images.githubusercontent.com/80831707/175773529-1fa7a4ad-04cf-41d8-9a52-14b26cdfb148.jpg)
![Screenshot_2022-06-25-20-22-02-594_com xayah databackup](https://user-images.githubusercontent.com/80831707/175773532-3e0449ec-dfc9-4398-a783-a5b8b1e64cc4.jpg)

**Comment by XayahSuSuSu** [comment]
感谢反馈，请问能否提供该模块以供测试

**Comment by vtrayy** [comment]
> 感谢反馈，请问能否提供该模块以供测试

模块链接https://github.com/VR-25/acc/releases/

**Comment by XayahSuSuSu** [comment]
此模块对于新版OTG检测逻辑影响较小，暂时关闭
