### ISSUE TITLE
[Bug] The app used a different version of ndk

### ISSUE THREAD

**Issue by linsui** [XayahSuSuSu/Android-DataBackup#321]
**Describe the bug**
The bin is built with ndk r25c. But the app requires ndk r25b because the ndkVersion is not set explicitly and the default ndk version is used.

**To Reproduce**

**Expected behavior**
The app uses the same ndk version as the bin.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Xiaomi 10 Ultra]
 - OS: [e.g. MIUI14, Android13]
 - Version [e.g. Beta-4.3.7]

**Additional context**
It should be enough to set the ndkVersion in https://github.com/XayahSuSuSu/Android-DataBackup/blob/main/source/core/rootservice/build.gradle.kts#L7.

**Comment by XayahSuSuSu** [comment]
> It should be enough to set the ndkVersion in https://github.com/XayahSuSuSu/Android-DataBackup/blob/main/source/core/rootservice/build.gradle.kts#L7.

I fixed ndkVersion in it, can we try it again?

**Comment by linsui** [comment]
It works, thanks!
