### ISSUE TITLE
[Bug] 无法访问备份文件 / Cannot access the backup files

### ISSUE THREAD

**Issue by Astoritin** [XayahSuSuSu/Android-DataBackup#330]
**Describe the bug**
在新安装Data Backup时，立即执行恢复操作时会一直处于正在加载，结果仍显示为空。
After Installing Data Backup, it will be loading for seconds and result is empty as executing restore.

**To Reproduce**
1. 安装 Data Backup 2.0.5 并完成引导页面的授权（我的面具版本是 Magisk Alpha 28101） / Install Data Backup 2.0.5 and finish granting permission in the welcome page (I am using Magisk Alpha 28101)
2. 备份目录选择外部存储，其他项目保持默认，点击完成 / Choose External Storage as the backup directory, keep other items by default and click on the "finish"
3. 点击快捷操作中的“恢复”/Click on "restore" under the quick actions title
4. 在恢复页面中单击应用 / Click on "Applications" in restore page.
5. 页面处于一直加载的状态，不久后显示为空 / The page is in the loading status and after a while it shows none

**Expected behavior**
1. 能够立即访问存储在外部存储的已备份应用 / Access the Backup Apps in the external storage.
2. 如果需要读写存储空间权限或者所有文件访问的权限（安卓11+），应该即时弹出权限申请或者在引导界面中完成对读写存储空间权限或所有文件访问的权限的授权。/ If need, DataBackup will show the grant permission dialog of READ_EXTERNAL_STORAGE / WRITE_EXTERNAL_STORAGE or MANAGE_EXTERNAL_STORAGE (Android 11 and higher) immediately or in the welcome page.

**Screenshots**
-

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 5 Pro / Redmi Note 9 Pro 5G China
 - OS: Project Matrixx 10.9.0, Android 14 QPR3 / HyperOS 2.0, Android 15 and MIUI 12.5, Android 11

**Additional context**
仅在全新安装的情况下会无法访问已备份在外部存储的应用，在通过 Rikka 的 App Ops 完成授权 所有文件访问权限 以后可以正常访问，并且哪怕清空数据并重新进入也能够访问了。由于DataBackup并未显式声明和索要该权限，系统设置里无法授予该权限，只能通过 App Ops 手工授权。

**Comment by XayahSuSuSu** [comment]
外部存储是指SD卡？

**Comment by Astoritin** [comment]
对的，sd卡
