### ISSUE TITLE
[Feature] App 清單畫面排序篩選

### ISSUE THREAD

**Issue by skysumbra** [XayahSuSuSu/Android-DataBackup#35]
原因：
目前備份和還原畫面中顯示的排序上到下推測試是
* 數字，除了英文之外的文字，英文大寫，英文小寫
不知道App 名稱時，需要手動尋找

目的
如有篩選功能時，啟用則可以作為一種找尋App 的方式
例如針對數字，除了英文之外的文字，英文大寫，英文小寫等篩選
將畫面的上App 呈現減少來找到目標App

**Comment by XayahSuSuSu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by XayahSuSuSu** [comment]
已在计划中，后续版本会跟进

**Comment by XayahSuSuSu** [comment]
请更新到最新版本，体验当前排序筛选方案，如有建议可重新Open。
https://github.com/XayahSuSuSu/Android-DataBackup/commit/327e5df9d66d8b149daa78a763b9d9f48b3724f2
