### ISSUE TITLE
[Feature] 支持使用Flyme系统备份文件来恢复

### ISSUE THREAD

**Issue by liujixings** [XayahSuSuSu/Android-DataBackup#37]
希望能够支持从Flyme系统的备份文件恢复
Flyme的备份是将apk以及data的压缩包放到目录中，并将所有应用的包名等放入app.info文件中，最后所有文件打包在一个压缩包中

这是[备份文件](https://wws.lanzoul.com/ik79P08hdiuh) 

![S20727-12532579](https://user-images.githubusercontent.com/36241123/181164794-841aa3de-748e-4993-a589-5f3f38725541.png)

**Comment by XayahSuSuSu** [comment]
Flyme的备份只能备份data目录吗，能否提供备份有user、data、obb的样本

**Comment by liujixings** [comment]
> Flyme的备份只能备份data目录吗，能否提供备份有user、data、obb的样本

只会备份/data/user目录下的，data和obb貌似并不会备份

**Comment by XayahSuSuSu** [comment]
> > Flyme的备份只能备份data目录吗，能否提供备份有user、data、obb的样本
> 
> 只会备份/data/user目录下的，data和obb貌似并不会备份

暂时不考虑加入Flyme备份支持
