### ISSUE TITLE
Apps doesn't work on Android 12.1

### ISSUE THREAD

**Issue by LeOS-GSI** [XayahSuSuSu/Android-DataBackup#38]
I'm using LeOS-GSi, a Android 12.1 without any google services. The device is rooted. But the app is not able to backup any apk or data or picture or any other content.
I like the UI, but I can't use it. Sorry

**Comment by XayahSuSuSu** [comment]
Thank you for supporting :)
Could you please offer more information about this?
Have you passed the environment detection?
Can you send me some logs?

**Comment by LeOS-GSI** [comment]
I'm sorry, I found a real great backup solution for none rooted. So I won't try/use your app anymore. Hope you will develop it further, because it will be a good solution for rooted devices
