### ISSUE TITLE
[Feature] 备份压缩格式求支持lz4

### ISSUE THREAD

**Issue by yzxzz** [XayahSuSuSu/Android-DataBackup#41]
介绍上看到支持LZ4，但是没找到地方切换
感觉设备恢复LZ4比zstd快很多（快50%以上），备份只大了10%左右

**Comment by XayahSuSuSu** [comment]
压缩方式在3.+支持切换，4.+版本还没有加回来，预计下个版本加回来

**Comment by XayahSuSuSu** [comment]
https://github.com/XayahSuSuSu/Android-DataBackup/commit/752b9fdff5d5ec6c8512257b6ee5bffb684fbd53
已实现
