### ISSUE TITLE
[Feature] 通过FTP 服务器、备份安装包

### ISSUE THREAD

**Issue by Pantyhose-X** [XayahSuSuSu/Android-DataBackup#43]
通过 [FTP 服务器](https://github.com/ppareit/swiftp) 把安装包传输到PC。不消耗存储空间

### 为什么要怎么做
最新版的应用不一定是最好的，网上找不到旧版的安装包。

如果手机坏了，或换新手机。PC上还有安装包，不用浪费大量时间在找旧版安装包上。

现在的市场上的安装包备份，都没有传输到其他地方的功能，都是备份到内部存储。没有足够的存储空间就备份不了。我安装了600多个应用30多G，没有足够的存储空间来备份。 

所以如果[FTP 服务器](https://github.com/ppareit/swiftp) 一个一个的把安装包传输到PC。我就可以备份了。

**Comment by XayahSuSuSu** [comment]
后续会支持WebDav，可以试试

**Comment by XayahSuSuSu** [comment]
https://github.com/XayahSuSuSu/Android-DataBackup/commit/327e5df9d66d8b149daa78a763b9d9f48b3724f2
