### ISSUE TITLE
[Feature] 导出备份的app安装包/恢复界面选择app时显示app版本号/不同时间备份的app可以选择不覆盖

### ISSUE THREAD

**Issue by bai12123** [XayahSuSuSu/Android-DataBackup#45]
1.导出备份的app安装包
   功能示例：在备份数据里，我有一个app暂时用不到，但是我需要这个app的安装包，就可以直接通过databackup导出安装包，而不需要将它恢复到手机上，再通过其他软件提取app安装包

2.恢复界面，选择恢复app时显示app版本号
   功能示例：在刷机恢复数据过程中，比如我发现了官网上app的最新版，如果在恢复界面选择app时，能够看到版本号，这样我就可以不选择这个app,直接在官网上下载最新版安装了。或者我在其他地方看到了旧版本，备份的app版本比它高，我也可以选择不恢复了

3.不同时间备份的app数据可以选择不覆盖
   功能示例：在不同时间备份的同一个app数据可以选择不覆盖原有数据

经常搞机，这3个功能对我是刚需了。

**Comment by XayahSuSuSu** [comment]
https://github.com/XayahSuSuSu/Android-DataBackup/commit/327e5df9d66d8b149daa78a763b9d9f48b3724f2
