### ISSUE TITLE
[Feature] SD card support

### ISSUE THREAD

**Issue by Mahantor** [XayahSuSuSu/Android-DataBackup#49]
Please add sd card support to the application Thankful

**Comment by XayahSuSuSu** [comment]
I don't have SD card in my phone, can you provide the absolute path?

**Comment by Mahantor** [comment]
I don't know how to program the application, but as far as I searched and understood, there is no need to know the address of the sd card, but I will still leave the location of the sd card for you, I hope it will be useful. I used mt manager /storage/4672-1E0D/

**Comment by XayahSuSuSu** [comment]
> I don't know how to program the application, but as far as I searched and understood, there is no need to know the address of the sd card, but I will still leave the location of the sd card for you, I hope it will be useful. /storage/4672-1E0D/ Or /mnt/media_rw/4672-1E0D/

 That's it, you can edit the path by select `/storage/4672-1E0D/` or `/mnt/media_rw/4672-1E0D/`
![83D352BFDB630E275DA249E6FEED4F53](https://user-images.githubusercontent.com/44322170/211957192-619250a7-92e5-4d68-8a0f-3f3c9410ed6b.jpg)
![AE53ABFB5D799D165003B867F781684C](https://user-images.githubusercontent.com/44322170/211957204-e6a27165-b86b-413f-a173-d88474e10646.jpg)
![BC9241FA3D5DD2A163B77C7BF77621B5](https://user-images.githubusercontent.com/44322170/211957213-e197d00b-dcb5-4135-a149-3617dc8e9318.jpg)

**Comment by XayahSuSuSu** [comment]
> Why can't I see this folder?
> 
> Redmi Note 9 Pro A12 Miui 13
> 
>  2023_01_12_06_06_34.mp4

Keep on going by clicking `...` and see, you should enter `/`, and find `/mnt`

**Comment by Mahantor** [comment]
Are you kidding yourself or me? I told you the problem, if you can't solve it, just say I can't
