### ISSUE TITLE
[Feature] 媒体备份改版

### ISSUE THREAD

**Issue by Goojoe** [XayahSuSuSu/Android-DataBackup#52]
## 媒体备份有很多不合理的地方

![IMG_20230115_011628](https://user-images.githubusercontent.com/78355492/212486502-0262c700-cc21-43e5-a55e-448336255846.jpg)

1. 横着排放，不够直观
2. 需要手动选择文件夹或文件，在大量文件需要备份的时候是灾难

基于以上提出请求：
1. 竖排，并且可以以文本方式编辑

**Comment by XayahSuSuSu** [comment]
目前长按Chip可以展开
另外媒体资料是基于文件夹备份，第二点大量文件能展开说说吗？

**Comment by Goojoe** [comment]
> 目前长按Chip可以展开 另外媒体资料是基于文件夹备份，第二点大量文件能展开说说吗？

Chip？是这个吗？
![IMG_20230115_150931](https://user-images.githubusercontent.com/78355492/212527803-5882d9a0-6cff-4c45-ba14-1567a504ee6d.jpg)

第二点可能说的有点夸张了，我的意思是：
如果以目前横排的方式：假如我要备份下面这样的列表会需要滑动非常长的列表，这太难管理了，而且容易出错

```
Download
DCIM
1
2
4
2
D
......
```

**Comment by XayahSuSuSu** [comment]
新版已修改为竖直排列

**Comment by Goojoe** [comment]
啊这，这个是设计可以。但是和我表达完全不同。我再解释一遍吧


✓ 以文本的形式存储媒体备份列表
![Screenshot_20230223-182848](https://user-images.githubusercontent.com/78355492/220882525-14554ca8-673b-4dbd-8db9-f3e9f22319be.png)

x 而不是手动一个个找到文件夹，并选择
![Screenshot_20230223-183146](https://user-images.githubusercontent.com/78355492/220882826-716f00c9-8c79-4451-9bd5-9245379cf61b.png)
