### ISSUE TITLE
[Feature] Android 兼容

### ISSUE THREAD

**Issue by Pantyhose-X** [XayahSuSuSu/Android-DataBackup#53]
如果 软件兼容 Android 8.0 不麻烦的话.

**Comment by XayahSuSuSu** [comment]
限制在Android9+主要是因为GNU Tar在用NDK交叉编译时API必须要>=28
可以参考这条[Commit](https://github.com/XayahSuSuSu/Android-DataBackup/commit/49cc6bc8a17cb3f620e33163a3607b5aad1c870d)
