### ISSUE TITLE
[BUG] App Crash

### ISSUE THREAD

**Issue by 10kumaranurag01** [XayahSuSuSu/Android-DataBackup#54]
> 

> 
![Screenshot_20230115-134116_DataBackup](https://user-images.githubusercontent.com/81381360/212529738-87d6c4ea-b86d-42e7-b274-9b51c35ecc2d.png)

**Comment by 10kumaranurag01** [comment]
I updated to latest version and when i launched the app this is showing.

**Comment by XayahSuSuSu** [comment]
> I updated to latest version and when i launched the app this is showing.

Check [Beta-4.3.0](https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/Beta-4.3.0!)
You need to delete previous backup or use this [tool](https://github.com/XayahSuSuSu/Android-DataBackup/issues/48)
