### ISSUE TITLE
[bug] 备份中的"覆盖"中文应考虑国际化,改为英文

### ISSUE THREAD

**Issue by Goojoe** [XayahSuSuSu/Android-DataBackup#55]
如果说只给中国用户服务,这没什么问题,但是还有英语和俄罗斯语服务用户,考虑到他们不一定支持UTF-8或者GBK,你应该把"覆盖"改为英文
![image](https://user-images.githubusercontent.com/78355492/212615595-7c4829d3-3d4e-4371-b79e-cd3eceaa2232.png)

**Comment by XayahSuSuSu** [comment]
应用在识别用户语言时会自动根据当前用户语言设定"覆盖"字符，如英文语言下该处为"Cover"
