### ISSUE TITLE
[Feature] Option to include/exclude Android/data 

### ISSUE THREAD

**Issue by Ivy-Tokito** [XayahSuSuSu/Android-DataBackup#58]
Option to include/exclude data from android/data folder 
Currently if you select data it selects all i think /data/data/*appdata is sufficient enough
It would be great to add option to include/exclude data from android/data

**Comment by XayahSuSuSu** [comment]
Thanks for advice, will take in account

**Comment by Tokito-Kun** [comment]
Any update on it ?
currently backing genshin settings is impossile without genshin data which is 30gb+ it could take around 45min+ for compression 
Any way to only backup genhin settings i.e data/**
Excluding android/data/** 

Currently app is awesome

**Comment by XayahSuSuSu** [comment]
> Any update on it ? currently backing genshin settings is impossile without genshin data which is 30gb+ it could take around 45min+ for compression Any way to only backup genhin settings i.e data/** Excluding android/data/**
> 
> Currently app is awesome

Nope, currently the cloud implement has higher priority, may delay this implementation.

**Comment by XayahSuSuSu** [comment]
![3fc9b16dfb5783869b5c8b7579c11564](https://github.com/XayahSuSuSu/Android-DataBackup/assets/44322170/904e4ca5-06e8-4260-888d-8a6f075be209)
Is this what you want?
Check in [CI builds](https://github.com/XayahSuSuSu/Android-DataBackup/actions/runs/7677651316).
