### ISSUE TITLE
[Feature] 挂载子路径设置项

### ISSUE THREAD

**Issue by UnderCooled** [XayahSuSuSu/Android-DataBackup#59]
https://github.com/XayahSuSuSu/Android-DataBackup/blob/c9721d480d40c92e378b1f5adfca54ca841b0950/app/src/main/java/com/xayah/databackup/util/ExtendCommand.kt#L158

根据 RCLONE 的说明文档：

> Paths are specified as `remote:sharename` (or remote: for the lsd command.) You may put subdirectories in too, e.g. `remote:item/path/to/dir`.

所以添加 SMB 类型配置时，应该多一个设置项来指定 `sharename/以及子路径` 。ExtendCommand.kt#L158 这里的 `${name}:` 后面应该加上对应的属性。

**Comment by XayahSuSuSu** [comment]
这里应该只是指定挂载子路径吧，不指定则是根目录，不过这里后续会添加相应设置项

**Comment by XayahSuSuSu** [comment]
下个版本将取消挂载功能，SMB已重新实现
