### ISSUE TITLE
[Feature] Default add magisk model directory

### ISSUE THREAD

**Issue by skysumbra** [XayahSuSuSu/Android-DataBackup#6]
Default add magisk model directory,
if magisk app install, backup model directory for default

**Comment by XayahSuSuSu** [comment]
> Default add magisk model directory, if magisk app install, backup model directory for default

Maybe will add this feature after refactoring.

**Comment by XayahSuSuSu** [comment]
For magisk models，you can type `/data/adb/modules` in `Custom directory` after updating.
