### ISSUE TITLE
[Bug] Termux app restoration issue

### ISSUE THREAD

**Issue by mizzunet** [XayahSuSuSu/Android-DataBackup#64]
**Describe the bug**
There are some permission issue on Termux after restoration.
![Screenshot_20230127-002600](https://user-images.githubusercontent.com/10193999/214924929-34b4fc07-f246-4ea4-8d24-d64209d8ea84.png)
Please look into this.
Thanks for this awesome app :)

**To Reproduce**
1. Install Termux
2. Backup it
3. Uninstall Termux
4. Restore
5. Open Termux and see the error

**Expected behavior**
Just get into shell.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: CalyxOS 13
 - Version: Beta-4.3.7

**Additional context**
I have tried other FOSS apps such as App Manager and NeoBackup. The same issue happens with AppManager restoration. But works fine with NeoBackup.

**Comment by XayahSuSuSu** [comment]
Thanks for feedback, it has been fixed in https://github.com/XayahSuSuSu/Android-DataBackup/commit/ce0495f37339e2a3dc14bfaaafc00f5e74bf82b6
