### ISSUE TITLE
[Bug] Search bar stays below status bar on scrolling down

### ISSUE THREAD

**Issue by mizzunet** [XayahSuSuSu/Android-DataBackup#65]
**Describe the bug**
The search box on app selection stays below status on scrolling down. Padding or margin issue I suppose

**To Reproduce**
1. Go to app selection
2. Scroll down a bit
3. Notice search bar position

**Expected behavior**
Itto become hidden or a search button to appear on top right corner as scrolling down

**Screenshots**
![Screenshot_20230127-143649_1](https://user-images.githubusercontent.com/10193999/215049806-ddab44dd-66ec-41db-8904-8c43900f5f9c.png)

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android13
 - Version Beta-4.3.7

**Comment by XayahSuSuSu** [comment]
(Somehow) FIxed in [1.0.0-alpha01](https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/1.0.0-alpha01)
