### ISSUE TITLE
[Bug] Problem with directory selection

### ISSUE THREAD

**Issue by Nimoshing** [XayahSuSuSu/Android-DataBackup#66]
**Describe the bug**
In most custom ROMs and sometimes even in original ROMs, the emulated, self and sd card folders are not displayed in the Storage branch. Why don't you use Google api to address and access external storage?

**To Reproduce**
1. Go to 'backup directory section'
2. Click on 'edit'
3. Click on 'sorage'
4. No folders are displayed for addressing

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [poco m2 pro]
 - OS: [miui 13 a12]
 - Version [stable 13.0.1]

**Additional context**

**Comment by XayahSuSuSu** [comment]
![image](https://user-images.githubusercontent.com/44322170/215543966-5266835f-fdc1-45c5-af74-66219f079583.png)
You mean this area is empty?
I use my own file picker to make the UI harmonious and easy to control.

**Comment by Nimoshing** [comment]
yes
What should I do to solve this problem?

**Comment by XayahSuSuSu** [comment]
> yes What should I do to solve this problem?

Try [**Beta-4.3.13**](https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/Beta-4.3.13)

**Comment by Nimoshing** [comment]
The problem still exists, except that in the otg section, an unsupported format error is displayed
And it is not selectable

![Screenshot_2023-02-01-02-37-51-780_com xayah databackup-edit](https://user-images.githubusercontent.com/123875061/215905110-3201f473-887d-42b0-bb63-1a4508e6f2ef.jpg)
![Screenshot_2023-02-01-02-38-19-757_com xayah databackup-edit](https://user-images.githubusercontent.com/123875061/215905146-c69d71a5-5d93-4fb2-b7d9-058a0a923785.jpg)

**Comment by Nimoshing** [comment]
I tested file selection on this ROM in the idm+ application and there was no problem


https://user-images.githubusercontent.com/123875061/216071994-846fc1d5-8061-4034-a12e-5418815a9273.mp4

**Comment by XayahSuSuSu** [comment]
> I tested file selection on this ROM in the idm+ application and there was no problem
> 
>  2023_02_01_17_54_32.mp4

vfat can only support files smaller than 4G, so it's unsupported filesystem.
But I will try to fix the empty `/storage` in the file picker.

**Comment by Nimoshing** [comment]
Just to remind you
I tested Beta 4.3.16fix and directory selection still not working

**Comment by XayahSuSuSu** [comment]
> Just to remind you I tested Beta 4.3.16fix and directory selection still not working

Thanks for reminding, haven't fixed it yet.
Will fix it when refactoring file picker.

**Comment by XayahSuSuSu** [comment]
Sry for the late response, can you give [it](https://github.com/XayahSuSuSu/AndroidModule-PickYou/releases/download/2.0.0/PickYouSample.apk) a try?

**Comment by Mahantor** [comment]
Thank you.the updates you've released in the last three months have completely solved my problem. I'm so glad you're paying so much attention to the user feedback I hope more new features will be added to the app

**Comment by XayahSuSuSu** [comment]
> Thank you.the updates you've released in the last three months have completely solved my problem. I'm so glad you're paying so much attention to the user feedback I hope more new features will be added to the app

:)
