### ISSUE TITLE
[Feature] Tap on app's card to select Application and Data at once

### ISSUE THREAD

**Issue by mizzunet** [XayahSuSuSu/Android-DataBackup#67]
**Describe the feature**
It would be quite handy if tapping on app's card area(shown as screenshot) to select/unselect Application and Data
![Screenshot_20230130-133759_1](https://user-images.githubusercontent.com/10193999/215422858-1d469454-5b46-4d09-8cbb-7bf2544d7059.png)

Thanks :)

**Comment by XayahSuSuSu** [comment]
Great idea
