### ISSUE TITLE
[Bug] 同时插入tf卡和otg会无法获取otg路径

### ISSUE THREAD

**Issue by Tonyha7** [XayahSuSuSu/Android-DataBackup#70]
**Describe the bug**
如题 安卓平板只插卡或者otg都会显示otg路径 但是同时插入就会无法获取otg路径

**Screenshots**
![MT管理器](https://img1.imgtp.com/2023/01/31/l6uHg42I.png)
![](https://img1.imgtp.com/2023/01/31/aFCdn5iL.png)

**Smartphone (please complete the following information):**
 - Device: Lenovo TB-X505F
 - OS: Android 10
 - Version: Beta-4.3.12

**Comment by XayahSuSuSu** [comment]
TF卡路径可以在/mnt/media_rw中找到吗？

**Comment by Tonyha7** [comment]
> TF卡路径可以在/mnt/media_rw中找到吗？

可以的

**Comment by XayahSuSuSu** [comment]
> > TF卡路径可以在/mnt/media_rw中找到吗？
> 
> 可以的

能否麻烦你在MT终端中输入`mount | grep "/mnt/media_rw" | awk '{print $3, $5}'`并截图或复制输出给我

**Comment by Tonyha7** [comment]
> > > TF卡路径可以在/mnt/media_rw中找到吗？
> > 
> > 
> > 可以的
> 
> 能否麻烦你在MT终端中输入`mount | grep "/mnt/media_rw" | awk '{print $3, $5}'`并截图或复制输出给我

这是同时插卡和otg的
/mnt/media_rw/1E71-B582 exfat
/mnt/runtime/default/1E71-B582 sdcardfs
/mnt/runtime/read/1E71-B582 sdcardfs
/mnt/runtime/write/1E71-B582 sdcardfs
/mnt/runtime/full/1E71-B582 sdcardfs
/storage/1E71-B582 sdcardfs
/mnt/media_rw/4E21-0000 exfat

**Comment by XayahSuSuSu** [comment]
> > > > TF卡路径可以在/mnt/media_rw中找到吗？
> > > 
> > > 
> > > 可以的
> > 
> > 
> > 能否麻烦你在MT终端中输入`mount | grep "/mnt/media_rw" | awk '{print $3, $5}'`并截图或复制输出给我
> 
> 这是同时插卡和otg的 /mnt/media_rw/1E71-B582 exfat /mnt/runtime/default/1E71-B582 sdcardfs /mnt/runtime/read/1E71-B582 sdcardfs /mnt/runtime/write/1E71-B582 sdcardfs /mnt/runtime/full/1E71-B582 sdcardfs /storage/1E71-B582 sdcardfs /mnt/media_rw/4E21-0000 exfat

感谢，能否再试试`mount | awk '$3 ~ /\mnt\/media_rw/ {print $3, $5}'`

**Comment by Tonyha7** [comment]
> 



> > > > > TF卡路径可以在/mnt/media_rw中找到吗？
> > > > 
> > > > 
> > > > 可以的
> > > 
> > > 
> > > 能否麻烦你在MT终端中输入`mount | grep "/mnt/media_rw" | awk '{print $3, $5}'`并截图或复制输出给我
> > 
> > 
> > 这是同时插卡和otg的 /mnt/media_rw/1E71-B582 exfat /mnt/runtime/default/1E71-B582 sdcardfs /mnt/runtime/read/1E71-B582 sdcardfs /mnt/runtime/write/1E71-B582 sdcardfs /mnt/runtime/full/1E71-B582 sdcardfs /storage/1E71-B582 sdcardfs /mnt/media_rw/4E21-0000 exfat
> 
> 感谢，能否再试试`mount | awk '$3 ~ /\/mnt\/media_rw/ {print $3, $5}'`

/mnt/media_rw/1E71-B582 exfat
/mnt/media_rw/4E21-0000 exfat

**Comment by XayahSuSuSu** [comment]
> > 
> 
> > > > > > TF卡路径可以在/mnt/media_rw中找到吗？
> > > > > 
> > > > > 
> > > > > 可以的
> > > > 
> > > > 
> > > > 能否麻烦你在MT终端中输入`mount | grep "/mnt/media_rw" | awk '{print $3, $5}'`并截图或复制输出给我
> > > 
> > > 
> > > 这是同时插卡和otg的 /mnt/media_rw/1E71-B582 exfat /mnt/runtime/default/1E71-B582 sdcardfs /mnt/runtime/read/1E71-B582 sdcardfs /mnt/runtime/write/1E71-B582 sdcardfs /mnt/runtime/full/1E71-B582 sdcardfs /storage/1E71-B582 sdcardfs /mnt/media_rw/4E21-0000 exfat
> > 
> > 
> > 感谢，能否再试试`mount | awk '$3 ~ /\/mnt\/media_rw/ {print $3, $5}'`
> 
> /mnt/media_rw/1E71-B582 exfat /mnt/media_rw/4E21-0000 exfat

已在 https://github.com/XayahSuSuSu/Android-DataBackup/commit/16b66ea0f2b24bfbb3e995550262065165fbd845 中修复，请等待下个版本推送
