### ISSUE TITLE
[Bug] 备份用户未检测到炼妖壶

### ISSUE THREAD

**Issue by WeeAris** [XayahSuSuSu/Android-DataBackup#71]
**Describe the bug**
尝试备份用户时未检测到炼妖壶及炼妖壶内应用

**Screenshots**
![Screenshot_20230131-222608](https://user-images.githubusercontent.com/123524343/215788575-14651559-a7b6-4c3d-bc92-782787113a48.png)
![Screenshot_20230131-222632](https://user-images.githubusercontent.com/123524343/215788705-9ba0dbfc-b871-4ea6-93ca-a8255bf171a5.png)
![Screenshot_20230131-222759](https://user-images.githubusercontent.com/123524343/215788806-529fd0c1-74ef-4de0-80cb-7f66fba728fd.png)

**Smartphone (please complete the following information):**
 - Device: Redmi K40S 
 - OS: Project Elixir 3.5, Android13
 - Version Beta-4.3.13

**Comment by XayahSuSuSu** [comment]
终端输入`ls -1 "/data/user"`截图看看

**Comment by WeeAris** [comment]
> 终端输入`ls -1 "/data/user"`截图看看

![Screenshot_20230201-105211](https://user-images.githubusercontent.com/123524343/215933759-749a64df-2bee-4ede-9335-5c1b2f9857b1.png)

**Comment by WeeAris** [comment]
Beta-4.3.14依然检测不到用户10（炼妖壶），以及用户12（平行空间）

**Comment by XayahSuSuSu** [comment]
https://github.com/tiann/KernelSU/issues/32
从该Issue来看，KernelSU并没有实现`--mount-master`，从你的结果来看也是如此，无法读出用户数据以及应用user数据

**Comment by XayahSuSuSu** [comment]
已在 https://github.com/XayahSuSuSu/Android-DataBackup/commit/a06286612e2dd93eccbcadb8b4d82f9ac491a998 中修复
