### ISSUE TITLE
[Bug] 不支持FAT32格式的外置设备

### ISSUE THREAD

**Issue by huangsijun17** [XayahSuSuSu/Android-DataBackup#74]
**Describe the bug**
插了个FAT32文件格式的U盘，显示不支持的格式。

**To Reproduce**
插了个FAT32文件格式的U盘。

**Expected behavior**
可以被选为外部设备。

**Screenshots**
![Screenshot_2023-02-05-16-23-43-31_0a93f116ed23bd6](https://user-images.githubusercontent.com/31504595/216809048-e1e0ead1-fc90-41fb-9915-541bf24e3335.jpg)

**Smartphone (please complete the following information):**
 - Device: 1+11
 - OS: COS13, Android13
 - Version: Beta-4.3.16fix

**Additional context**

**Comment by XayahSuSuSu** [comment]
Fat23/Vfat 单文件最大只能支持4GB，不适用于部分备份场景，建议格式化为ntfs或exfat

**Comment by nanami157** [comment]
Try to Add split files system feature As all custom rom doesn't support exfat. but fat32 is universal..
