### ISSUE TITLE
[Bug] too much gallery folds

### ISSUE THREAD

**Issue by Ichigokano** [XayahSuSuSu/Android-DataBackup#75]
**Describe the bug**
As title

**Screenshots**
![Screenshot_2023-02-05-19-33-09-912_com miui gallery](https://user-images.githubusercontent.com/83592381/216816498-a68d531b-969f-4b84-9ff0-2106db36568d.jpg)

 - Device: [Redmi K50]
 - OS: [MIUI13, Android12]
 - Version [Beta-4.3.16-fix]

**Comment by XayahSuSuSu** [comment]
Try creating a new empty file name `.nomedia` in `DataBackup`, and see if it will solve.

**Comment by Ichigokano** [comment]
> Try creating a new empty file name `.nomedia` in `DataBackup`, and see if it will solve.

Thanks.It does work.But why not create it automatically when create 'DataBackup' folder

**Comment by XayahSuSuSu** [comment]
> > Try creating a new empty file name `.nomedia` in `DataBackup`, and see if it will solve.
> 
> Thanks.It does work.But why not create it automatically when create 'DataBackup' folder

Just have a check, will add this feature later.
