### ISSUE TITLE
[Bug] App's name and icon not displaying for baclup taken using older version

### ISSUE THREAD

**Issue by mizzunet** [XayahSuSuSu/Android-DataBackup#76]
**Describe the bug**
On latesr beta(Beta-4.3.17), App's name and icon aren't appearing for backups taken using Beta-4.3.9. Instead they are "The retrieved app" which I suppose a placeholder.
![Screenshot_20230206-120512](https://user-images.githubusercontent.com/10193999/216901080-b61780c6-dba0-4a4b-96dc-bcb6888ea727.png)

Whereas, displays fine for the ones taken from latest version itself(Beta-4.3.17)

**To Reproduce**
1. Install Beta-4.3.9
2. Take some backup of apps
3. Install Beta-4.3.17
4. Get Restore page
5. See error

**Expected behavior**
Display them.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: CalyxOS
 - Version: Beta-4.3.17

**Additional context**
IMO, This page in the older versions was better,
![Screenshot_20230206-120715](https://user-images.githubusercontent.com/10193999/216901658-401d6d9f-336c-4167-b352-a798faed2c5d.png)

Thanks

**Comment by XayahSuSuSu** [comment]
Yes, it's sitll in Beta stage, so the configuration or something else will change frequently.
