### ISSUE TITLE
[Feature] 快速赋予预编译文件权限建议

### ISSUE THREAD

**Issue by Goojoe** [XayahSuSuSu/Android-DataBackup#79]
![Screenshot_20230208-165850](https://user-images.githubusercontent.com/78355492/217483076-63524f90-cd8f-4faf-86d2-f384b2f8b3cb.png)

这个界面可以加上命令快速复制方便赋权限，慢慢找太麻烦了 Rclone预编译文件也是类似的
```
su
```

```
chmod 777 /data/user/0/com.xayah.databackup/files/bin/*
```
提示，上面两个需要分别执行

**Comment by XayahSuSuSu** [comment]
Good idea
