### ISSUE TITLE
[Feature] 备份并还原应用的 Android ID (SSAID)

### ISSUE THREAD

**Issue by huyz-git** [XayahSuSuSu/Android-DataBackup#81]
**Describe the feature**

有部分（银行类）应用在登录时会检测 Android ID (SSAID)，如果 Android ID 变了就会认定为是新设备，要求重新验证登录。而刷机之后应用的 Android ID 会变，单纯备份还原数据不会改变 Android ID。

各应用的 SSAID 存放在 `/data/system/users/<userid>/settings_ssaid.xml` 里，这是一个 binary XML，备份 SSAID 只需要将它转码并记录下来即可。
还原 SSAID 则可能需要用户手动操作，因为应用只有首次请求过 SSAID 才会在这个文件里出现相应的条目（新安装的应用在没有启动之前，这里是没有相应的条目的）。具体如何修改可以参考 https://github.com/MuntashirAkon/AppManager 。

**Comment by XayahSuSuSu** [comment]
```
   <setting
        id="90"
        name="10404"
        value="
        package="me.zhanghai.android.files"
        defaultValue="
        defaultSysSet-bool="false"
        tag="null" />
```
尚未清楚id生成规则，否则可以尝试直接重建？

**Comment by XayahSuSuSu** [comment]
请提供测试样例，适时重开该Issue
