### ISSUE TITLE
[Feature] "Installed" filter and indicator

### ISSUE THREAD

**Issue by mizzunet** [XayahSuSuSu/Android-DataBackup#84]
**Describe the feature**
Please add a filter for Installed apps and an indicator in app cards if the app is installed.
This would be helpful in case having plenty of app backups and some are restored, and want to restore the ones that aren't installed.

Thanks :)

**Comment by XayahSuSuSu** [comment]
Added in [1.0.0-alpha04](https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/1.0.0-alpha04)

**Comment by XayahSuSuSu** [comment]
> ![Screenshot_20230227-145214](https://user-images.githubusercontent.com/10193999/221524115-483382e0-3f3f-4f9c-8a29-7503ba3fc671.png)
> 
> I installed alpha04, I can't seem to find the indicator

It's in restore list.
