### ISSUE TITLE
[Feature] 特定备份保护

### ISSUE THREAD

**Issue by yutouyes** [XayahSuSuSu/Android-DataBackup#85]
**Describe the feature**
内容: 类似钛备份的保护此备份
![Screenshot_2023-02-19-22-58-27-06_e2956caca62cc71](https://user-images.githubusercontent.com/17039457/219956241-c49e4e38-8a82-49eb-8d79-deb957574ba6.jpg)
对某个备份数据（备份A）进行保护后，下一次备份（备份B）不会覆盖备份A，下下次备份（备份C）会覆盖备份B，与备份A一起保存，同理D E F ... 后面的备份都只会占用一份空间，最新的那个和备份A一起保存，中间的全部覆盖。
这样相比分时备份更节省一点空间，保存的备份数据包的数量也能下降。关键的备份也不会被覆盖。

**Comment by XayahSuSuSu** [comment]
2.0.0已实现
