### ISSUE TITLE
[Bug] LazyColumn 的性能问题

### ISSUE THREAD

**Issue by purofle** [XayahSuSuSu/Android-DataBackup#86]
https://github.com/XayahSuSuSu/Android-DataBackup/blob/23ea46dc7b991c121fddb0f2d1ee0fd825e81cff/app/src/main/java/com/xayah/databackup/compose/ui/activity/guide/components/Introduction.kt#L30-L40

类似于这种地方 LazyColumn 会引起掉帧, 似乎可以通过 Releases 编译跟设置 key 来解决。

参考：https://stackoverflow.com/questions/70592694/laggy-lazy-column-android-compose

**Comment by XayahSuSuSu** [comment]
感谢，R8将会在最后进行完整测试后开启

**Comment by mymine** [comment]
> 感谢，R8将会在最后进行完整测试后开启
R8出错部分用proguard-rules.pro排除掉
https://developer.android.com/studio/build/shrink-code?utm_source=android-studio&hl=zh-cn#shrink-resources
