### ISSUE TITLE
[Bug] 部分非0用户应用无法被备份程序检测到的问题

### ISSUE THREAD

**Issue by WeeAris** [XayahSuSuSu/Android-DataBackup#87]
**Describe the bug**
仅安装于炼妖壶内，在0用户中无分身的应用无法被备份程序检测到，无法直接备份，必须向0用户中创建分身之后才能被检测到。

**To Reproduce**
在炼妖壶内通过应用商店或apk文件安装0用户中未安装的应用，或通过备份文件直接恢复到非0用户中，然后尝试备份。

**Expected behavior**
非0用户应用无论是否在0用户中存在分身，均可直接备份。

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [Redmi K40S]
 - OS: [ArrowOS, Android13]
 - Version [Beta-4.3.16~1.0.0-alpha01]

**Additional context**

**Comment by XayahSuSuSu** [comment]
已于[1.0.0-alpha03](https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/1.0.0-alpha03)修复
