### ISSUE TITLE
[Bug] stuck during backup

### ISSUE THREAD

**Issue by Mahantor** [XayahSuSuSu/Android-DataBackup#88]
**Describe the bug**
I installed the latest version (alpha), but the application freezes when backing up 

**Smartphone
Xiaomi redmi note 9 pro
Joyeuse
Miui 13 android 12
Global rom 13.0.4

**Comment by XayahSuSuSu** [comment]
Ref: https://issuetracker.google.com/issues/269402895
Related: https://github.com/XayahSuSuSu/Android-DataBackup/commit/3659910da37df661d23f6b0b8514899b1b95f7db

**Comment by XayahSuSuSu** [comment]
Fixed in [1.0.0-alpha02](https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/1.0.0-alpha02)
