### ISSUE TITLE
功能请求示例 [Feature request example]

### ISSUE THREAD

**Issue by XayahSuSuSu** [XayahSuSuSu/Android-DataBackup#9]
中文:
标题: `[Feature] WebDav适配`
内容(可空): `支持WebDav`

English:
Title: `[Feature] WebDav adaptation`
Content(Nullable): `Support for WebDav`

**Comment by wjz983** [comment]
<img width="1080" height="676" alt="Image" src="https://github.com/user-attachments/assets/7360941b-7f5b-4700-a987-354db1f03341" />能加个说明吗？这几个分别代表备份什么，有点看不懂！对号好像是全部备份，安卓图标是只备份apk吗？柱状只备份数据？
