### ISSUE TITLE
[Feature] 失败自动重试

### ISSUE THREAD

**Issue by Akaccia** [XayahSuSuSu/Android-DataBackup#90]
今天备份的时候微信莫名失败了，但1.00-alpha2版本好像不会自动重试备份失败的app，我又重新进行了一次备份（因为不想重新设置备份哪些app的设置，所以似乎不能反选微信）。这次备份成功了，但需要消耗大量的时间检查没有改动的app，所以希望加入某个app失败后在最后重试的功能。

**Comment by XayahSuSuSu** [comment]
计划于`1.0.0-alpha04`添加

**Comment by XayahSuSuSu** [comment]
已于[1.0.0-alpha05](https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/1.0.0-alpha05)添加
