### ISSUE TITLE
[Feature] Unselect selection after going back from the list

### ISSUE THREAD

**Issue by mizzunet** [XayahSuSuSu/Android-DataBackup#92]
**Describe the bug**
It is kinda a bug that, when you choose some apps in the list of either for restoring/backing up and you did it. Then you went back to main page or reopened the app, the apps you selected earlier are appears to be still selected.

**To Reproduce**
1. You backup for apps A,B,C
2. You want to restore A and B
3. You restored and went back or closed the DataBackup
4. Later you want to restore app C
5. In the app list, the apps A and B are still selected.

**Expected behavior**
No apps should be selected. So, you can select C and do restore.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android13
 - Version: 1.0.0-alpha04

**Additional context**
If there were many of apps, you only realise that A and B are also selected when it's start restoring

**Comment by XayahSuSuSu** [comment]
Sounds like a feature request instead of bug report.

**Comment by XayahSuSuSu** [comment]
Check in [1.0.0-rc01](https://github.com/XayahSuSuSu/Android-DataBackup/releases/tag/1.0.0-rc01)
