### ISSUE TITLE
[Feature] Publish on F-Droid

### ISSUE THREAD

**Issue by ghost** [XayahSuSuSu/Android-DataBackup#94]
**Describe the feature**
The app is already on IzzyOnDroid but it would be nice to have it in the main repo

**Comment by XayahSuSuSu** [comment]
https://gitlab.com/fdroid/rfp/-/issues/2227
Still have some stuffs to finish

**Comment by XayahSuSuSu** [comment]
https://github.com/XayahSuSuSu/Android-DataBackup/commit/72c66520d20855263c5f10b1a5952b285faca77c
