### ISSUE TITLE
[Feature] Need toggle with exclude APP cache backup and some more

### ISSUE THREAD

**Issue by La-Hire** [XayahSuSuSu/Android-DataBackup#98]
Some app save media data in cache which won't be backup, so if it is possible to add a toggle to backup cache?

**Comment by XayahSuSuSu** [comment]
![image](https://user-images.githubusercontent.com/44322170/222402962-6204a7c1-5bd4-4d0e-b4d9-06d098898808.jpg)

You mean `cache` and `code_cache` or only `cache` in `user`/`data`/`obb`?

**Comment by La-Hire** [comment]
cache and code_cache in /data/data/packagename/
some web games app save media in cache
